-- Create ATS_INT database and apply TRUSTEES + CHAPTER_DETAILS schema.
-- Idempotent: safe to re-run.

IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'ATS_INT')
  CREATE DATABASE ATS_INT
GO

USE ATS_INT
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TRUSTEES')
BEGIN
  CREATE TABLE TRUSTEES (
    ID            INT          NOT NULL PRIMARY KEY,
    LAST_NAME     VARCHAR(50)  NULL,
    FIRST_NAME    VARCHAR(50)  NULL,
    MIDDLE        VARCHAR(50)  NULL,
    COMPANY       VARCHAR(100) NULL,
    STREET        VARCHAR(100) NULL,
    STREET1       VARCHAR(100) NULL,  -- address line 2 (primary address)
    CITY          VARCHAR(50)  NULL,
    STATE         CHAR(2)      NULL,
    ZIP           VARCHAR(10)  NULL,
    ZIP_PLUS      VARCHAR(5)   NULL,
    DISP_ON_WEB   CHAR(1)      NULL,
    DISP_ON_WEB_A2 CHAR(1)     NULL,
    STREET_A2     VARCHAR(100) NULL,
    STREET1_A2    VARCHAR(100) NULL,  -- address line 2 (A2 address)
    CITY_A2       VARCHAR(50)  NULL,
    STATE_A2      CHAR(2)      NULL,
    ZIP_A2        VARCHAR(10)  NULL,
    ZIP_PLUS_A2   VARCHAR(5)   NULL,
    TELEPHONE     VARCHAR(20)  NULL,
    EMAIL_ADDRESS VARCHAR(100) NULL
  )
END
GO

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CHAPTER_DETAILS')
BEGIN
  CREATE TABLE CHAPTER_DETAILS (
    TRU_ID          INT          NOT NULL,
    DISTRICT        VARCHAR(50)  NULL,
    SERVING_STATE   CHAR(2)      NULL,
    CHAPTER         VARCHAR(10)  NULL,
    APPOINTED_DATE  DATE         NULL,
    STATUS          CHAR(5)      NULL,
    STATUS_EFF_DATE DATE         NULL,
    ARCHIVE_DATE    DATE         NULL
  )
END
GO
