-- Seed ACMS Replica Test Database with Mock Data
-- Run this on the acms_replica_test database
--
-- Creates mock CMMAP (appointments) and supporting tables
-- for integration testing of the downstream CMMAP view

USE acms_replica_test;
GO

-- Drop existing tables if they exist
IF OBJECT_ID('dbo.CMMAP', 'U') IS NOT NULL DROP TABLE dbo.CMMAP;
IF OBJECT_ID('dbo.CMMPR', 'U') IS NOT NULL DROP TABLE dbo.CMMPR;
IF OBJECT_ID('dbo.CMMPT', 'U') IS NOT NULL DROP TABLE dbo.CMMPT;
GO

-- Create CMMPR (Professional Master) table
CREATE TABLE CMMPR (
    DELETE_CODE CHAR(1) NOT NULL DEFAULT ' ',
    PROF_CODE NUMERIC(5,5) NOT NULL,
    GROUP_DESIGNATOR CHAR(2) NOT NULL,
    PROF_LAST_NAME CHAR(20),
    PROF_FIRST_NAME CHAR(15),
    PROF_MI CHAR(1),
    PROF_ADDRESS1 CHAR(30),
    PROF_ADDRESS2 CHAR(30),
    PROF_CITY CHAR(20),
    PROF_STATE CHAR(2),
    PROF_ZIP CHAR(10),
    UPDATE_DATE DATETIME2(3),
    PRIMARY KEY (PROF_CODE, GROUP_DESIGNATOR)
);
GO

-- Create CMMPT (Professional Types) table
CREATE TABLE CMMPT (
    DELETE_CODE CHAR(1) NOT NULL DEFAULT ' ',
    PROF_TYPE CHAR(2) NOT NULL,
    PROF_TYPE_DESC CHAR(20),
    GROUP_DESIGNATOR CHAR(2) NOT NULL,
    PRIMARY KEY (PROF_TYPE, GROUP_DESIGNATOR)
);
GO

-- Create CMMAP (Appointments Master) table
CREATE TABLE CMMAP (
    DELETE_CODE CHAR(1) NOT NULL DEFAULT ' ',
    CASE_DIV NUMERIC(5,3) NOT NULL,
    CASE_YEAR NUMERIC(5,2) NOT NULL,
    CASE_NUMBER NUMERIC(5,5) NOT NULL,
    RECORD_SEQ_NBR NUMERIC(5,5) NOT NULL,
    PROF_CODE NUMERIC(5,5) NOT NULL,
    APPT_TYPE CHAR(2) NOT NULL,
    APPT_DATE NUMERIC(9,11),
    APPT_DISP CHAR(2),
    DISP_DATE NUMERIC(9,11),
    COMMENTS CHAR(30),
    APPTEE_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    ALPHA_SEARCH CHAR(30),
    USER_ID CHAR(10),
    HEARING_SEQUENCE NUMERIC(5,5),
    REGION_CODE CHAR(2),
    GROUP_DESIGNATOR CHAR(2) NOT NULL,
    RGN_CREATE_DATE NUMERIC(5,8),
    RGN_UPDATE_DATE NUMERIC(5,8),
    CDB_CREATE_DATE NUMERIC(5,8),
    CDB_UPDATE_DATE NUMERIC(5,8),
    APPT_DATE_DT DATETIME2(3),
    DISP_DATE_DT DATETIME2(3),
    RGN_CREATE_DATE_DT DATETIME2(3),
    RGN_UPDATE_DATE_DT DATETIME2(3),
    CDB_CREATE_DATE_DT DATETIME2(3),
    CDB_UPDATE_DATE_DT DATETIME2(3),
    CASE_FULL_ACMS AS (
        RIGHT('000' + CAST(CASE_DIV AS VARCHAR), 3) + '-' +
        RIGHT('00' + CAST(CASE_YEAR AS VARCHAR), 2) + '-' +
        RIGHT('00000' + CAST(CASE_NUMBER AS VARCHAR), 5)
    ) PERSISTED,
    UPDATE_DATE DATETIME2(3),
    REPLICATED_DATE DATETIME2(3),
    id INT IDENTITY(1,1) PRIMARY KEY,
    RRN INT
);
GO

-- Seed Professional Types
INSERT INTO CMMPT (DELETE_CODE, PROF_TYPE, PROF_TYPE_DESC, GROUP_DESIGNATOR) VALUES
(' ', 'TR', 'Trustee', 'NY'),
(' ', 'AT', 'Attorney', 'NY'),
(' ', 'S1', 'Staff Type 1', 'NY'),
(' ', 'S2', 'Staff Type 2', 'NY'),
(' ', 'TR', 'Trustee', 'CA'),
(' ', 'AT', 'Attorney', 'CA'),
(' ', 'S1', 'Staff Type 1', 'CA'),
(' ', 'S2', 'Staff Type 2', 'CA');
GO

-- Seed Professionals
INSERT INTO CMMPR (DELETE_CODE, PROF_CODE, GROUP_DESIGNATOR, PROF_LAST_NAME, PROF_FIRST_NAME, PROF_MI, PROF_CITY, PROF_STATE, UPDATE_DATE) VALUES
(' ', 123, 'NY', 'Smith', 'John', 'Q', 'New York', 'NY', GETDATE()),
(' ', 456, 'NY', 'Doe', 'Jane', 'M', 'Brooklyn', 'NY', GETDATE()),
(' ', 789, 'CA', 'Johnson', 'Robert', 'L', 'Los Angeles', 'CA', GETDATE()),
(' ', 111, 'NY', 'Williams', 'Sarah', 'A', 'Manhattan', 'NY', GETDATE()),
(' ', 222, 'CA', 'Brown', 'Michael', 'T', 'San Francisco', 'CA', GETDATE());
GO

-- Seed ACMS Case Appointments
-- Case 1: Chapter 7 with trustee (NY-00123)
INSERT INTO CMMAP (
    DELETE_CODE, CASE_DIV, CASE_YEAR, CASE_NUMBER, RECORD_SEQ_NBR,
    PROF_CODE, GROUP_DESIGNATOR, APPT_TYPE,
    APPT_DATE, APPT_DATE_DT,
    APPTEE_ACTIVE, ALPHA_SEARCH, USER_ID,
    CDB_CREATE_DATE, CDB_UPDATE_DATE, CDB_CREATE_DATE_DT, CDB_UPDATE_DATE_DT,
    UPDATE_DATE
) VALUES
(' ', 081, 24, 12345, 1,
 123, 'NY', 'TR',
 20240115, '2024-01-15',
 'Y', 'SMITH', 'ACMS',
 20240115, 20240115, '2024-01-15', '2024-01-15',
 GETDATE());
GO

-- Case 2: Chapter 11 with trustee (CA-00789)
INSERT INTO CMMAP (
    DELETE_CODE, CASE_DIV, CASE_YEAR, CASE_NUMBER, RECORD_SEQ_NBR,
    PROF_CODE, GROUP_DESIGNATOR, APPT_TYPE,
    APPT_DATE, APPT_DATE_DT,
    APPTEE_ACTIVE, ALPHA_SEARCH, USER_ID,
    CDB_CREATE_DATE, CDB_UPDATE_DATE, CDB_CREATE_DATE_DT, CDB_UPDATE_DATE_DT,
    UPDATE_DATE
) VALUES
(' ', 081, 24, 23456, 1,
 789, 'CA', 'TR',
 20240201, '2024-02-01',
 'Y', 'JOHNSON', 'ACMS',
 20240201, 20240201, '2024-02-01', '2024-02-01',
 GETDATE());
GO

-- Case 3: Chapter 13 with trustee (NY-00456)
INSERT INTO CMMAP (
    DELETE_CODE, CASE_DIV, CASE_YEAR, CASE_NUMBER, RECORD_SEQ_NBR,
    PROF_CODE, GROUP_DESIGNATOR, APPT_TYPE,
    APPT_DATE, APPT_DATE_DT,
    APPTEE_ACTIVE, ALPHA_SEARCH, USER_ID,
    CDB_CREATE_DATE, CDB_UPDATE_DATE, CDB_CREATE_DATE_DT, CDB_UPDATE_DATE_DT,
    UPDATE_DATE
) VALUES
(' ', 081, 24, 34567, 1,
 456, 'NY', 'TR',
 20240310, '2024-03-10',
 'Y', 'DOE', 'ACMS',
 20240310, 20240310, '2024-03-10', '2024-03-10',
 GETDATE());
GO

-- Case 4: Chapter 15 with attorney (NY-00111) - THIS WILL BE OVERRIDDEN BY CAMS
INSERT INTO CMMAP (
    DELETE_CODE, CASE_DIV, CASE_YEAR, CASE_NUMBER, RECORD_SEQ_NBR,
    PROF_CODE, GROUP_DESIGNATOR, APPT_TYPE,
    APPT_DATE, APPT_DATE_DT,
    APPTEE_ACTIVE, ALPHA_SEARCH, USER_ID,
    CDB_CREATE_DATE, CDB_UPDATE_DATE, CDB_CREATE_DATE_DT, CDB_UPDATE_DATE_DT,
    UPDATE_DATE
) VALUES
(' ', 081, 24, 99999, 1,
 111, 'NY', 'S1',
 20240401, '2024-04-01',
 'Y', 'WILLIAMS', 'ACMS',
 20240401, 20240401, '2024-04-01', '2024-04-01',
 GETDATE());
GO

-- Case 5: Chapter 15 with attorney (CA-00222) - NO CAMS OVERRIDE
INSERT INTO CMMAP (
    DELETE_CODE, CASE_DIV, CASE_YEAR, CASE_NUMBER, RECORD_SEQ_NBR,
    PROF_CODE, GROUP_DESIGNATOR, APPT_TYPE,
    APPT_DATE, APPT_DATE_DT,
    APPTEE_ACTIVE, ALPHA_SEARCH, USER_ID,
    CDB_CREATE_DATE, CDB_UPDATE_DATE, CDB_CREATE_DATE_DT, CDB_UPDATE_DATE_DT,
    UPDATE_DATE
) VALUES
(' ', 081, 24, 88888, 1,
 222, 'CA', 'S1',
 20240415, '2024-04-15',
 'Y', 'BROWN', 'ACMS',
 20240415, 20240415, '2024-04-15', '2024-04-15',
 GETDATE());
GO

PRINT 'ACMS replica seeded with ' + CAST(@@ROWCOUNT AS VARCHAR) + ' appointments';
PRINT '';
PRINT 'Test Cases:';
PRINT '  081-24-12345: Chapter 7 (ACMS only, no CAMS override)';
PRINT '  081-24-23456: Chapter 11 (ACMS only, no CAMS override)';
PRINT '  081-24-34567: Chapter 13 (ACMS only, no CAMS override)';
PRINT '  081-24-99999: Chapter 15 (ACMS data exists, WILL BE overridden by CAMS)';
PRINT '  081-24-88888: Chapter 15 (ACMS only, no CAMS override)';
GO
