#!/bin/bash

# Demo Search Examples
# This script demonstrates all search capabilities using demo mode

echo "=========================================="
echo "Phonetic & Nickname Search Demo"
echo "=========================================="
echo ""
echo "Make sure to start the backend with DEMO_MODE=true first:"
echo "  DEMO_MODE=true npm run start:api"
echo ""
echo "Then run these curl commands to test each feature:"
echo ""

API_BASE="http://localhost:3000/api/v1"

echo "1️⃣  NICKNAME MATCHING"
echo "-------------------------------------------"
echo "Search: Mike (finds Michael Johnson + Mike Anderson)"
echo "curl \"${API_BASE}/cases?debtorName=Mike&offset=0&limit=25\""
echo ""
echo "Search: Bill Smith (finds William Smith)"
echo "curl \"${API_BASE}/cases?debtorName=Bill%20Smith&offset=0&limit=25\""
echo ""
echo "Search: Bob (finds Robert Brown + Bob Wilson)"
echo "curl \"${API_BASE}/cases?debtorName=Bob&offset=0&limit=25\""
echo ""

echo "2️⃣  PHONETIC MATCHING"
echo "-------------------------------------------"
echo "Search: Jon (finds John, Jon, Jonathan but NOT Jane)"
echo "curl \"${API_BASE}/cases?debtorName=Jon&offset=0&limit=25\""
echo ""
echo "Search: Smith (finds Smith + Smyth)"
echo "curl \"${API_BASE}/cases?debtorName=Smith&offset=0&limit=25\""
echo ""

echo "3️⃣  PARTIAL WORD MATCHING"
echo "-------------------------------------------"
echo "Search: john sm (finds John Smith)"
echo "curl \"${API_BASE}/cases?debtorName=john%20sm&offset=0&limit=25\""
echo ""
echo "Search: mik joh (finds Michael Johnson)"
echo "curl \"${API_BASE}/cases?debtorName=mik%20joh&offset=0&limit=25\""
echo ""

echo "4️⃣  JOINT DEBTOR SEARCH"
echo "-------------------------------------------"
echo "Search: Mike Harris (finds James Harris with joint debtor Michael Harris)"
echo "curl \"${API_BASE}/cases?debtorName=Mike%20Harris&offset=0&limit=25\""
echo ""

echo "5️⃣  FALSE POSITIVE PREVENTION"
echo "-------------------------------------------"
echo "Search: Jane (finds Jane cases)"
echo "curl \"${API_BASE}/cases?debtorName=Jane&offset=0&limit=25\""
echo ""
echo "Search: Jon (does NOT find Jane - filtered by Jaro-Winkler)"
echo "curl \"${API_BASE}/cases?debtorName=Jon&offset=0&limit=25\""
echo ""

echo "6️⃣  CHAPTER FILTERING"
echo "-------------------------------------------"
echo "Search: Mike in Chapter 7 only (finds Michael Johnson)"
echo "curl \"${API_BASE}/cases?debtorName=Mike&chapters=7&offset=0&limit=25\""
echo ""
echo "Search: Mike in Chapter 15 only (finds Mike Anderson)"
echo "curl \"${API_BASE}/cases?debtorName=Mike&chapters=15&offset=0&limit=25\""
echo ""
echo "Search: All Chapter 7 cases"
echo "curl \"${API_BASE}/cases?chapters=7&offset=0&limit=25\""
echo ""

echo "=========================================="
echo "To run these commands automatically:"
echo "  chmod +x demo-search-examples.sh"
echo "  ./demo-search-examples.sh | grep -A1 'curl' | grep curl | sh"
echo "=========================================="
