/**
 * Scenario: cases-fuzzy-search
 * Database: cams only
 *
 * Seeds cases with diverse debtor names to support fuzzy search testing:
 *
 *   - Phonetic variations (John vs Jon, Cathy vs Kathy, Steven vs Stephen)
 *   - Jane variations (Jane vs Jayne vs Jaine)
 *   - Common misspellings (Smith vs Smyth, Jennifer vs Jenifer)
 *   - Arab names with spelling variations (Mohammed/Muhammad/Mohamed, Ahmad/Ahmed, Fatima/Fatimah, Khalid/Khaled)
 *   - Middle name variations (John Q. Public vs John Quincy Public)
 *   - Hyphenated names (Mary Smith-Jones)
 *   - Joint debtors with different last names
 *   - Special characters (O'Brien)
 *   - Very long names (testing truncation)
 *   - Very short names (testing minimums)
 *
 * NOTE: Uses existing DXTR cases across multiple districts - no DXTR seeding required.
 */

import type { SeedContext, SeedOperation } from '../../runner.js';
import { faker } from '@faker-js/faker';
import { generateSearchTokens } from '../lib/phonetic-tokens.js';

const SEEDER = { id: 'SEED', name: 'Test Data Seeder' };

// Helper to generate case with specific debtor name
function createCase(opts: {
  caseId: string;
  dxtrId: string;
  caseNumber: string;
  debtorName: string;
  chapter: string;
  division: string;
  divisionName: string;
  city: string;
  state: string;
  regionId: string;
  regionName: string;
  courtId: string;
}) {
  const officeCode = `USTP_CAMS_Region_${opts.regionId}_Office_${opts.division}`;
  return {
    id: opts.caseId,
    documentType: 'SYNCED_CASE',
    dxtrId: opts.dxtrId,
    caseId: opts.caseId,
    caseNumber: opts.caseNumber,
    chapter: opts.chapter,
    caseTitle: opts.debtorName,
    dateFiled: '2026-01-15',
    officeName: opts.divisionName,
    officeCode,
    courtId: opts.courtId,
    courtName: `U.S. Bankruptcy Court ${opts.divisionName}`,
    courtDivisionCode: opts.division,
    courtDivisionName: opts.divisionName,
    groupDesignator: opts.state,
    regionId: opts.regionId,
    regionName: opts.regionName,
    consolidation: [],
    debtor: {
      name: opts.debtorName,
      phoneticTokens: generateSearchTokens(opts.debtorName),
      address1: faker.location.streetAddress(),
      address2: undefined,
      address3: undefined,
      cityStateZipCountry: `${opts.city}, ${opts.state} ${faker.location.zipCode()}`,
      taxId: undefined,
      ssn: undefined,
    },
    updatedOn: '2026-01-15T10:00:00.000Z',
    updatedBy: SEEDER,
  };
}

export async function generate(_ctx: SeedContext): Promise<SeedOperation[]> {
  const cases = [
    // 1. John Anderson
    createCase({
      caseId: '081-26-63921',
      dxtrId: '318723',
      caseNumber: '26-63921',
      debtorName: 'John Anderson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 2. Jon Anderson
    createCase({
      caseId: '081-87-50941',
      dxtrId: '318545',
      caseNumber: '87-50941',
      debtorName: 'Jon Anderson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 3. Cathy Martinez
    createCase({
      caseId: '081-27-10491',
      dxtrId: '318288',
      caseNumber: '27-10491',
      debtorName: 'Cathy Martinez',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 4. Kathy Martinez
    createCase({
      caseId: '081-91-06221',
      dxtrId: '318205',
      caseNumber: '91-06221',
      debtorName: 'Kathy Martinez',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 5. Steven Wilson
    createCase({
      caseId: '081-82-08111',
      dxtrId: '318203',
      caseNumber: '82-08111',
      debtorName: 'Steven Wilson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 6. Stephen Wilson
    createCase({
      caseId: '081-13-35011',
      dxtrId: '318202',
      caseNumber: '13-35011',
      debtorName: 'Stephen Wilson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 7. Robert Smith
    createCase({
      caseId: '081-51-51841',
      dxtrId: '318035',
      caseNumber: '51-51841',
      debtorName: 'Robert Smith',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 8. Robert Smyth
    createCase({
      caseId: '081-56-78971',
      dxtrId: '317937',
      caseNumber: '56-78971',
      debtorName: 'Robert Smyth',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 9. Jennifer Brown
    createCase({
      caseId: '081-94-55601',
      dxtrId: '317865',
      caseNumber: '94-55601',
      debtorName: 'Jennifer Brown',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 10. Jenifer Browne
    createCase({
      caseId: '081-24-47791',
      dxtrId: '317588',
      caseNumber: '24-47791',
      debtorName: 'Jenifer Browne',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 11. Michael Johnson
    createCase({
      caseId: '081-73-31081',
      dxtrId: '317587',
      caseNumber: '73-31081',
      debtorName: 'Michael Johnson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 12. Michael R. Johnson
    createCase({
      caseId: '081-96-45961',
      dxtrId: '317586',
      caseNumber: '96-45961',
      debtorName: 'Michael R. Johnson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 13. Michael Robert Johnson
    createCase({
      caseId: '081-32-46421',
      dxtrId: '316506',
      caseNumber: '32-46421',
      debtorName: 'Michael Robert Johnson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 14. Sarah Lee
    createCase({
      caseId: '081-33-88951',
      dxtrId: '315958',
      caseNumber: '33-88951',
      debtorName: 'Sarah Lee',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 15. Sarah Elizabeth Lee
    createCase({
      caseId: '081-43-45611',
      dxtrId: '315956',
      caseNumber: '43-45611',
      debtorName: 'Sarah Elizabeth Lee',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 16. Mary Smith-Jones
    createCase({
      caseId: '081-94-40931',
      dxtrId: '315954',
      caseNumber: '94-40931',
      debtorName: 'Mary Smith-Jones',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 17. Mary Smith Jones
    createCase({
      caseId: '081-86-76881',
      dxtrId: '315952',
      caseNumber: '86-76881',
      debtorName: 'Mary Smith Jones',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 18. David Parker-Thompson
    createCase({
      caseId: '081-65-67641',
      dxtrId: '315951',
      caseNumber: '65-67641',
      debtorName: 'David Parker-Thompson',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 19. James Williams and Patricia Rodriguez
    createCase({
      caseId: '081-57-17261',
      dxtrId: '315949',
      caseNumber: '57-17261',
      debtorName: 'James Williams and Patricia Rodriguez',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 20. Christopher Taylor and Amanda Chen
    createCase({
      caseId: '081-82-07091',
      dxtrId: '315136',
      caseNumber: '82-07091',
      debtorName: 'Christopher Taylor and Amanda Chen',
      chapter: '15',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    // 21. Patrick O'Brien
    createCase({
      caseId: '091-99-21596',
      dxtrId: '998692',
      caseNumber: '99-21596',
      debtorName: "Patrick O'Brien",
      chapter: '11',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 22. Sean O'Connor-MacDonald
    createCase({
      caseId: '091-99-64660',
      dxtrId: '996105',
      caseNumber: '99-64660',
      debtorName: "Sean O'Connor-MacDonald",
      chapter: '11',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 27. Montgomery Bartholomew Wellington-Fitzpatrick III
    createCase({
      caseId: '091-99-05433',
      dxtrId: '995787',
      caseNumber: '99-05433',
      debtorName: 'Montgomery Bartholomew Wellington-Fitzpatrick III',
      chapter: '11',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 28. Alexandra Penelope Victoria Kensington-Ashworth and Maximilian Theodore Christopher Pemberton-Smythe
    createCase({
      caseId: '091-99-75623',
      dxtrId: '995576',
      caseNumber: '99-75623',
      debtorName:
        'Alexandra Penelope Victoria Kensington-Ashworth and Maximilian Theodore Christopher Pemberton-Smythe',
      chapter: '12',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 29. Li Wu
    createCase({
      caseId: '091-99-74857',
      dxtrId: '995164',
      caseNumber: '99-74857',
      debtorName: 'Li Wu',
      chapter: '12',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 30. Bo Kim
    createCase({
      caseId: '091-99-78269',
      dxtrId: '993583',
      caseNumber: '99-78269',
      debtorName: 'Bo Kim',
      chapter: '11',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 31. Jo Lee
    createCase({
      caseId: '091-99-58624',
      dxtrId: '992262',
      caseNumber: '99-58624',
      debtorName: 'Jo Lee',
      chapter: '12',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 32. Catherine Davis
    createCase({
      caseId: '091-99-39312',
      dxtrId: '991810',
      caseNumber: '99-39312',
      debtorName: 'Catherine Davis',
      chapter: '15',
      division: '091',
      divisionName: 'Buffalo',
      city: 'Buffalo',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    // 33. Katherine Davis
    createCase({
      caseId: '111-30-07761',
      dxtrId: '191604',
      caseNumber: '30-07761',
      debtorName: 'Katherine Davis',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 34. Jane Thompson
    createCase({
      caseId: '111-90-62941',
      dxtrId: '191602',
      caseNumber: '90-62941',
      debtorName: 'Jane Thompson',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 35. Jayne Thompson
    createCase({
      caseId: '111-12-39891',
      dxtrId: '191206',
      caseNumber: '12-39891',
      debtorName: 'Jayne Thompson',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 36. Jaine Thompson
    createCase({
      caseId: '111-45-80671',
      dxtrId: '190777',
      caseNumber: '45-80671',
      debtorName: 'Jaine Thompson',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 37. Mohammed Ali
    createCase({
      caseId: '111-83-76271',
      dxtrId: '190408',
      caseNumber: '83-76271',
      debtorName: 'Mohammed Ali',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 38. Muhammad Ali
    createCase({
      caseId: '111-98-67871',
      dxtrId: '190407',
      caseNumber: '98-67871',
      debtorName: 'Muhammad Ali',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 39. Mohamed Ali
    createCase({
      caseId: '111-48-40001',
      dxtrId: '190398',
      caseNumber: '48-40001',
      debtorName: 'Mohamed Ali',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 40. Ahmad Hassan
    createCase({
      caseId: '111-32-37881',
      dxtrId: '190397',
      caseNumber: '32-37881',
      debtorName: 'Ahmad Hassan',
      chapter: '15',
      division: '111',
      divisionName: 'Chicago',
      city: 'Chicago',
      state: 'IL',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0711',
    }),
    // 41. Ahmed Hassan
    createCase({
      caseId: '674-75-55581',
      dxtrId: '98369',
      caseNumber: '75-55581',
      debtorName: 'Ahmed Hassan',
      chapter: '12',
      division: '674',
      divisionName: 'Unknown',
      city: 'Unknown',
      state: 'UK',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0674',
    }),
    // 42. Fatima Hussein
    createCase({
      caseId: '674-98-89371',
      dxtrId: '96284',
      caseNumber: '98-89371',
      debtorName: 'Fatima Hussein',
      chapter: '12',
      division: '674',
      divisionName: 'Unknown',
      city: 'Unknown',
      state: 'UK',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0674',
    }),
    // 43. Fatimah Hussein
    createCase({
      caseId: '674-43-54281',
      dxtrId: '95778',
      caseNumber: '43-54281',
      debtorName: 'Fatimah Hussein',
      chapter: '12',
      division: '674',
      divisionName: 'Unknown',
      city: 'Unknown',
      state: 'UK',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0674',
    }),
    // 44. Khalid Ibrahim
    createCase({
      caseId: '674-13-10371',
      dxtrId: '95771',
      caseNumber: '13-10371',
      debtorName: 'Khalid Ibrahim',
      chapter: '12',
      division: '674',
      divisionName: 'Unknown',
      city: 'Unknown',
      state: 'UK',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0674',
    }),
    // 45. Khaled Ibrahim
    createCase({
      caseId: '674-69-10431',
      dxtrId: '94882',
      caseNumber: '69-10431',
      debtorName: 'Khaled Ibrahim',
      chapter: '12',
      division: '674',
      divisionName: 'Unknown',
      city: 'Unknown',
      state: 'UK',
      regionId: '11',
      regionName: 'CHICAGO',
      courtId: '0674',
    }),
  ];

  return [
    {
      db: 'cams',
      collectionOrTable: 'cases',
      data: cases,
    },
  ];
}
