/**
 * Scenario: cases-fuzzy-search
 * Database: cams only
 *
 * Seeds 43 cases with diverse debtor names to support fuzzy search testing:
 *
 *   - Phonetic variations (John vs Jon, Cathy vs Kathy, Steven vs Stephen)
 *   - Jane variations (Jane vs Jayne vs Jaine)
 *   - Common misspellings (Smith vs Smyth, Jennifer vs Jenifer)
 *   - Arab names with spelling variations (Mohammed/Muhammad/Mohamed, Ahmad/Ahmed, Fatima/Fatimah, Khalid/Khaled)
 *   - Middle name variations (John Q. Public vs John Quincy Public)
 *   - Hyphenated names (Mary Smith-Jones)
 *   - Joint debtors with different last names
 *   - Special characters (O'Brien, José García, François Müller)
 *   - Very long names (testing truncation)
 *   - Very short names (testing minimums)
 *
 * NOTE: Uses existing DXTR cases across multiple districts - no DXTR seeding required.
 */

import type { SeedContext, SeedOperation } from '../../runner.js';
import { faker } from '@faker-js/faker';
import { generateSearchTokens } from '../lib/phonetic-tokens.js';

const SEEDER = { id: 'SEED', name: 'Test Data Seeder' };

// Helper to generate case with specific debtor name
function createCase(opts: {
  caseId: string;
  dxtrId: string;
  caseNumber: string;
  debtorName: string;
  chapter: string;
  division: string;
  divisionName: string;
  city: string;
  state: string;
  regionId: string;
  regionName: string;
  courtId: string;
}) {
  const officeCode = `USTP_CAMS_Region_${opts.regionId}_Office_${opts.division}`;
  return {
    id: opts.caseId,
    documentType: 'SYNCED_CASE',
    dxtrId: opts.dxtrId,
    caseId: opts.caseId,
    caseNumber: opts.caseNumber,
    chapter: opts.chapter,
    caseTitle: opts.debtorName,
    dateFiled: '2026-01-15',
    officeName: opts.divisionName,
    officeCode,
    courtId: opts.courtId,
    courtName: `U.S. Bankruptcy Court ${opts.divisionName}`,
    courtDivisionCode: opts.division,
    courtDivisionName: opts.divisionName,
    groupDesignator: opts.state,
    regionId: opts.regionId,
    regionName: opts.regionName,
    consolidation: [],
    debtor: {
      name: opts.debtorName,
      phoneticTokens: generateSearchTokens(opts.debtorName),
      address1: faker.location.streetAddress(),
      address2: undefined,
      address3: undefined,
      cityStateZipCountry: `${opts.city}, ${opts.state} ${faker.location.zipCode()}`,
      taxId: undefined,
      ssn: undefined,
    },
    updatedOn: '2026-01-15T10:00:00.000Z',
    updatedBy: SEEDER,
  };
}

export async function generate(_ctx: SeedContext): Promise<SeedOperation[]> {
  const cases = [
    // ── Phonetic Variations ──────────────────────────────────────────────────
    createCase({
      caseId: '081-26-80001',
      dxtrId: 'FUZZ80001',
      caseNumber: '26-80001',
      debtorName: 'John Anderson',
      chapter: '7',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    createCase({
      caseId: '081-26-80002',
      dxtrId: 'FUZZ80002',
      caseNumber: '26-80002',
      debtorName: 'Jon Anderson',
      chapter: '7',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    createCase({
      caseId: '081-26-80003',
      dxtrId: 'FUZZ80003',
      caseNumber: '26-80003',
      debtorName: 'Cathy Martinez',
      chapter: '11',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    createCase({
      caseId: '081-26-80004',
      dxtrId: 'FUZZ80004',
      caseNumber: '26-80004',
      debtorName: 'Kathy Martinez',
      chapter: '11',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    createCase({
      caseId: '081-26-80005',
      dxtrId: 'FUZZ80005',
      caseNumber: '26-80005',
      debtorName: 'Steven Wilson',
      chapter: '7',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    createCase({
      caseId: '081-26-80006',
      dxtrId: 'FUZZ80006',
      caseNumber: '26-80006',
      debtorName: 'Stephen Wilson',
      chapter: '7',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),

    // ── Common Misspellings ──────────────────────────────────────────────────
    createCase({
      caseId: '091-26-80007',
      dxtrId: 'FUZZ80007',
      caseNumber: '26-80007',
      debtorName: 'Robert Smith',
      chapter: '13',
      division: '091',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    createCase({
      caseId: '091-26-80008',
      dxtrId: 'FUZZ80008',
      caseNumber: '26-80008',
      debtorName: 'Robert Smyth',
      chapter: '13',
      division: '091',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    createCase({
      caseId: '091-26-80009',
      dxtrId: 'FUZZ80009',
      caseNumber: '26-80009',
      debtorName: 'Jennifer Brown',
      chapter: '7',
      division: '091',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),
    createCase({
      caseId: '091-26-80010',
      dxtrId: 'FUZZ80010',
      caseNumber: '26-80010',
      debtorName: 'Jenifer Browne',
      chapter: '7',
      division: '091',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0209',
    }),

    // ── Middle Name Variations ───────────────────────────────────────────────
    createCase({
      caseId: '923-26-80011',
      dxtrId: 'FUZZ80011',
      caseNumber: '26-80011',
      debtorName: 'Michael Johnson',
      chapter: '11',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),
    createCase({
      caseId: '923-26-80012',
      dxtrId: 'FUZZ80012',
      caseNumber: '26-80012',
      debtorName: 'Michael R. Johnson',
      chapter: '11',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),
    createCase({
      caseId: '923-26-80013',
      dxtrId: 'FUZZ80013',
      caseNumber: '26-80013',
      debtorName: 'Michael Robert Johnson',
      chapter: '11',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),
    createCase({
      caseId: '923-26-80014',
      dxtrId: 'FUZZ80014',
      caseNumber: '26-80014',
      debtorName: 'Sarah Lee',
      chapter: '7',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),
    createCase({
      caseId: '923-26-80015',
      dxtrId: 'FUZZ80015',
      caseNumber: '26-80015',
      debtorName: 'Sarah Elizabeth Lee',
      chapter: '7',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),

    // ── Hyphenated Names ─────────────────────────────────────────────────────
    createCase({
      caseId: '225-26-80016',
      dxtrId: 'FUZZ80016',
      caseNumber: '26-80016',
      debtorName: 'Mary Smith-Jones',
      chapter: '13',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80017',
      dxtrId: 'FUZZ80017',
      caseNumber: '26-80017',
      debtorName: 'Mary Smith Jones',
      chapter: '13',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80018',
      dxtrId: 'FUZZ80018',
      caseNumber: '26-80018',
      debtorName: 'David Parker-Thompson',
      chapter: '7',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),

    // ── Joint Debtors with Different Last Names ──────────────────────────────
    createCase({
      caseId: '225-26-80019',
      dxtrId: 'FUZZ80019',
      caseNumber: '26-80019',
      debtorName: 'James Williams and Patricia Rodriguez',
      chapter: '13',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80020',
      dxtrId: 'FUZZ80020',
      caseNumber: '26-80020',
      debtorName: 'Christopher Taylor and Amanda Chen',
      chapter: '7',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),

    // ── Special Characters ───────────────────────────────────────────────────
    createCase({
      caseId: '940-26-80021',
      dxtrId: 'FUZZ80021',
      caseNumber: '26-80021',
      debtorName: "Patrick O'Brien",
      chapter: '11',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
    createCase({
      caseId: '940-26-80022',
      dxtrId: 'FUZZ80022',
      caseNumber: '26-80022',
      debtorName: 'José García',
      chapter: '7',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
    createCase({
      caseId: '940-26-80023',
      dxtrId: 'FUZZ80023',
      caseNumber: '26-80023',
      debtorName: 'François Müller',
      chapter: '13',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
    createCase({
      caseId: '940-26-80024',
      dxtrId: 'FUZZ80024',
      caseNumber: '26-80024',
      debtorName: "Sean O'Connor-MacDonald",
      chapter: '7',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),

    // ── Very Long Names ──────────────────────────────────────────────────────
    createCase({
      caseId: '001-26-80025',
      dxtrId: 'FUZZ80025',
      caseNumber: '26-80025',
      debtorName: 'Montgomery Bartholomew Wellington-Fitzpatrick III',
      chapter: '11',
      division: '001',
      divisionName: 'Anchorage',
      city: 'Anchorage',
      state: 'AK',
      regionId: '18',
      regionName: 'SEATTLE',
      courtId: '0901',
    }),
    createCase({
      caseId: '001-26-80026',
      dxtrId: 'FUZZ80026',
      caseNumber: '26-80026',
      debtorName:
        'Alexandra Penelope Victoria Kensington-Ashworth and Maximilian Theodore Christopher Pemberton-Smythe',
      chapter: '13',
      division: '001',
      divisionName: 'Anchorage',
      city: 'Anchorage',
      state: 'AK',
      regionId: '18',
      regionName: 'SEATTLE',
      courtId: '0901',
    }),

    // ── Very Short Names ─────────────────────────────────────────────────────
    createCase({
      caseId: '001-26-80027',
      dxtrId: 'FUZZ80027',
      caseNumber: '26-80027',
      debtorName: 'Li Wu',
      chapter: '7',
      division: '001',
      divisionName: 'Anchorage',
      city: 'Anchorage',
      state: 'AK',
      regionId: '18',
      regionName: 'SEATTLE',
      courtId: '0901',
    }),
    createCase({
      caseId: '001-26-80028',
      dxtrId: 'FUZZ80028',
      caseNumber: '26-80028',
      debtorName: 'Bo Kim',
      chapter: '7',
      division: '001',
      divisionName: 'Anchorage',
      city: 'Anchorage',
      state: 'AK',
      regionId: '18',
      regionName: 'SEATTLE',
      courtId: '0901',
    }),
    createCase({
      caseId: '001-26-80029',
      dxtrId: 'FUZZ80029',
      caseNumber: '26-80029',
      debtorName: 'Jo Lee',
      chapter: '13',
      division: '001',
      divisionName: 'Anchorage',
      city: 'Anchorage',
      state: 'AK',
      regionId: '18',
      regionName: 'SEATTLE',
      courtId: '0901',
    }),

    // ── Additional Common Variations (Catherine/Katherine) ───────────────────
    createCase({
      caseId: '081-26-80030',
      dxtrId: 'FUZZ80030',
      caseNumber: '26-80030',
      debtorName: 'Catherine Davis',
      chapter: '11',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),
    createCase({
      caseId: '081-26-80031',
      dxtrId: 'FUZZ80031',
      caseNumber: '26-80031',
      debtorName: 'Katherine Davis',
      chapter: '11',
      division: '081',
      divisionName: 'Manhattan',
      city: 'New York',
      state: 'NY',
      regionId: '02',
      regionName: 'NEW YORK',
      courtId: '0208',
    }),

    // ── Jane Variations ──────────────────────────────────────────────────────
    createCase({
      caseId: '923-26-80032',
      dxtrId: 'FUZZ80032',
      caseNumber: '26-80032',
      debtorName: 'Jane Thompson',
      chapter: '7',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),
    createCase({
      caseId: '923-26-80033',
      dxtrId: 'FUZZ80033',
      caseNumber: '26-80033',
      debtorName: 'Jayne Thompson',
      chapter: '7',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),
    createCase({
      caseId: '923-26-80034',
      dxtrId: 'FUZZ80034',
      caseNumber: '26-80034',
      debtorName: 'Jaine Thompson',
      chapter: '7',
      division: '923',
      divisionName: 'Dallas',
      city: 'Dallas',
      state: 'TX',
      regionId: '06',
      regionName: 'DALLAS',
      courtId: '0561',
    }),

    // ── Arab Names with Different Spellings ──────────────────────────────────
    createCase({
      caseId: '225-26-80035',
      dxtrId: 'FUZZ80035',
      caseNumber: '26-80035',
      debtorName: 'Mohammed Ali',
      chapter: '11',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80036',
      dxtrId: 'FUZZ80036',
      caseNumber: '26-80036',
      debtorName: 'Muhammad Ali',
      chapter: '11',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80037',
      dxtrId: 'FUZZ80037',
      caseNumber: '26-80037',
      debtorName: 'Mohamed Ali',
      chapter: '11',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80038',
      dxtrId: 'FUZZ80038',
      caseNumber: '26-80038',
      debtorName: 'Ahmad Hassan',
      chapter: '7',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '225-26-80039',
      dxtrId: 'FUZZ80039',
      caseNumber: '26-80039',
      debtorName: 'Ahmed Hassan',
      chapter: '7',
      division: '225',
      divisionName: 'Los Angeles',
      city: 'Los Angeles',
      state: 'CA',
      regionId: '17',
      regionName: 'LOS ANGELES',
      courtId: '0921',
    }),
    createCase({
      caseId: '940-26-80040',
      dxtrId: 'FUZZ80040',
      caseNumber: '26-80040',
      debtorName: 'Fatima Hussein',
      chapter: '13',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
    createCase({
      caseId: '940-26-80041',
      dxtrId: 'FUZZ80041',
      caseNumber: '26-80041',
      debtorName: 'Fatimah Hussein',
      chapter: '13',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
    createCase({
      caseId: '940-26-80042',
      dxtrId: 'FUZZ80042',
      caseNumber: '26-80042',
      debtorName: 'Khalid Ibrahim',
      chapter: '7',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
    createCase({
      caseId: '940-26-80043',
      dxtrId: 'FUZZ80043',
      caseNumber: '26-80043',
      debtorName: 'Khaled Ibrahim',
      chapter: '7',
      division: '940',
      divisionName: 'Tampa',
      city: 'Tampa',
      state: 'FL',
      regionId: '21',
      regionName: 'TAMPA',
      courtId: '1162',
    }),
  ];

  return [
    {
      db: 'cams',
      collectionOrTable: 'cases',
      data: cases,
    },
  ];
}
