// TODO: Fakerize this list of trial attorneys.
export const ATTORNEYS = [
  {
    firstName: 'Linda',
    middleName: 'A',
    lastName: 'Riffkin',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY001',
    userName: 'lariffkin',
  },
  {
    firstName: 'Susan',
    middleName: '',
    lastName: 'Arbeit',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY002',
    userName: 'sarbeit',
  },
  {
    firstName: 'Mark',
    middleName: '',
    lastName: 'Bruh',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY003',
    userName: 'mbruh',
  },
  {
    firstName: 'Shara',
    middleName: '',
    lastName: 'Cornell',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY004',
    userName: 'scornell',
  },
  {
    firstName: 'Brian',
    middleName: 'S',
    lastName: 'Masumoto',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY005',
    userName: 'bsmasumoto',
  },
  {
    firstName: 'Andrea',
    middleName: 'B',
    lastName: 'Schwartz',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY006',
    userName: 'abschwartz',
  },
  {
    firstName: 'Paul',
    middleName: 'K',
    lastName: 'Schwartzberg',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY007',
    userName: 'pkschwartzberg',
  },
  {
    firstName: 'Shannon',
    middleName: '',
    lastName: 'Scott',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY008',
    userName: 'sscott',
  },
  {
    firstName: 'Tara',
    middleName: '',
    lastName: 'Tiantian',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY009',
    userName: 'ttiantian',
  },
  {
    firstName: 'Andy',
    middleName: '',
    lastName: 'Velez-Rivera',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY010',
    userName: 'avelezrivera',
  },
  {
    firstName: 'Daniel',
    middleName: '',
    lastName: 'Rudewicz',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY011',
    userName: 'drudewicz',
  },
  {
    firstName: 'Annie',
    middleName: '',
    lastName: 'Wells',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY012',
    userName: 'awells',
  },
  {
    firstName: 'Greg',
    middleName: 'M',
    lastName: 'Zipes',
    generation: '',
    office: 'Manhattan',
    userId: 'ATY013',
    userName: 'gmzipes',
  },
];
