import { OfficeDetails } from '../courts';

/***************************************************************************\
 * !! The Following Offices are aligend with legitimate court divisions
 *    as found in the adapters/gateways/dxtr/dxtr.constants.ts file.
 *    Because many of our tests will take an office at random out of
 *    this list, and then do a lookup in dxtr.constants.ts ( which is
 *    used in our live system ), DO NOT ADD mock offices to this file.
 \***************************************************************************/
export const OFFICES: OfficeDetails[] = [
  {
    courtDivisionCode: '710',
    groupDesignator: 'AK',
    courtId: '097-',
    officeName: '',
    officeCode: '1',
    state: 'AK',
    courtName: 'District of Alaska',
    courtDivisionName: 'Juneau',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '720',
    groupDesignator: 'AK',
    courtId: '097-',
    officeName: '',
    officeCode: '2',
    state: 'AK',
    courtName: 'District of Alaska',
    courtDivisionName: 'Nome',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '730',
    groupDesignator: 'AK',
    courtId: '097-',
    officeName: '',
    officeCode: '3',
    state: 'AK',
    courtName: 'District of Alaska',
    courtDivisionName: 'Anchorage',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '740',
    groupDesignator: 'AK',
    courtId: '097-',
    officeName: '',
    officeCode: '4',
    state: 'AK',
    courtName: 'District of Alaska',
    courtDivisionName: 'Fairbanks',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '750',
    groupDesignator: 'AK',
    courtId: '097-',
    officeName: '',
    officeCode: '5',
    state: 'AK',
    courtName: 'District of Alaska',
    courtDivisionName: 'Ketchikan',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '061',
    groupDesignator: 'AL',
    courtId: '0206',
    officeName: '',
    officeCode: '1',
    state: 'NY',
    courtName: 'Northern District of New York',
    courtDivisionName: 'Albany',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '102',
    groupDesignator: 'AL',
    courtId: '0210',
    officeName: '',
    officeCode: '2',
    state: 'VT',
    courtName: 'District of Vermont',
    courtDivisionName: 'Burlington',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '084',
    groupDesignator: 'AL',
    courtId: '0208',
    officeName: '',
    officeCode: '4',
    state: 'NY',
    courtName: 'Southern District of New York',
    courtDivisionName: 'Poughkeepsie',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '105',
    groupDesignator: 'AL',
    courtId: '0210',
    officeName: '',
    officeCode: '5',
    state: 'VT',
    courtName: 'District of Vermont',
    courtDivisionName: 'Rutland',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '841',
    groupDesignator: 'AQ',
    courtId: '1084',
    officeName: '',
    officeCode: '1',
    state: 'NM',
    courtName: 'District of New Mexico',
    courtDivisionName: 'Albuquerque',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '3E1',
    groupDesignator: 'AT',
    courtId: '113E',
    officeName: '',
    officeCode: '1',
    state: 'GA',
    courtName: 'Northern District of Georgia',
    courtDivisionName: 'Atlanta',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '911',
    groupDesignator: 'AT',
    courtId: '0391',
    officeName: '',
    officeCode: '1',
    state: 'VI',
    courtName: 'United States Virgin Islands',
    courtDivisionName: 'St. Croix',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3E2',
    groupDesignator: 'AT',
    courtId: '113E',
    officeName: '',
    officeCode: '2',
    state: 'GA',
    courtName: 'Northern District of Georgia',
    courtDivisionName: 'Gainesville',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3E3',
    groupDesignator: 'AT',
    courtId: '113E',
    officeName: '',
    officeCode: '3',
    state: 'GA',
    courtName: 'Northern District of Georgia',
    courtDivisionName: 'Newnan',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '913',
    groupDesignator: 'AT',
    courtId: '0391',
    officeName: '',
    officeCode: '3',
    state: 'VI',
    courtName: 'United States Virgin Islands',
    courtDivisionName: 'St. Thomas',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3E4',
    groupDesignator: 'AT',
    courtId: '113E',
    officeName: '',
    officeCode: '4',
    state: 'GA',
    courtName: 'Northern District of Georgia',
    courtDivisionName: 'Rome',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '421',
    groupDesignator: 'AU',
    courtId: '0542',
    officeName: '',
    officeCode: '1',
    state: 'TX',
    courtName: 'Western District of Texas',
    courtDivisionName: 'Austin',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '426',
    groupDesignator: 'AU',
    courtId: '0542',
    officeName: '',
    officeCode: '6',
    state: 'TX',
    courtName: 'Western District of Texas',
    courtDivisionName: 'Waco',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '427',
    groupDesignator: 'AU',
    courtId: '0542',
    officeName: '',
    officeCode: '7',
    state: 'TX',
    courtName: 'Western District of Texas',
    courtDivisionName: 'Midland',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '221',
    groupDesignator: 'AX',
    courtId: '0422',
    officeName: '',
    officeCode: '1',
    state: 'VA',
    courtName: 'Eastern District of Virginia',
    courtDivisionName: 'Alexandria',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '901',
    groupDesignator: 'AX',
    courtId: '0090',
    officeName: '',
    officeCode: '1',
    state: 'DC',
    courtName: 'District of Columbia',
    courtDivisionName: 'Washington, D.C."',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '161',
    groupDesignator: 'BA',
    courtId: '0416',
    officeName: '',
    officeCode: '1',
    state: 'MD',
    courtName: 'District of Maryland',
    courtDivisionName: 'Baltimore',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '011',
    groupDesignator: 'BO',
    courtId: '0101',
    officeName: '',
    officeCode: '1',
    state: 'MA',
    courtName: 'District of Massachusetts',
    courtDivisionName: 'Boston',
    regionId: '01',
    regionName: 'BOSTON',
  },
  {
    courtDivisionCode: '071',
    groupDesignator: 'BR',
    courtId: '0207',
    officeName: '',
    officeCode: '1',
    state: 'NY',
    courtName: 'Eastern District of New York',
    courtDivisionName: 'Brooklyn',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '761',
    groupDesignator: 'BS',
    courtId: '0976',
    officeName: '',
    officeCode: '1',
    state: 'ID',
    courtName: 'District of Idaho',
    courtDivisionName: 'Boise',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '762',
    groupDesignator: 'BS',
    courtId: '0976',
    officeName: '',
    officeCode: '2',
    state: 'ID',
    courtName: 'District of Idaho',
    courtDivisionName: 'Coeur dAlene',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '763',
    groupDesignator: 'BS',
    courtId: '0976',
    officeName: '',
    officeCode: '3',
    state: 'ID',
    courtName: 'District of Idaho',
    courtDivisionName: 'Moscow',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '764',
    groupDesignator: 'BS',
    courtId: '0976',
    officeName: '',
    officeCode: '4',
    state: 'ID',
    courtName: 'District of Idaho',
    courtDivisionName: 'Pocatello',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '768',
    groupDesignator: 'BS',
    courtId: '0976',
    officeName: '',
    officeCode: '8',
    state: 'ID',
    courtName: 'District of Idaho',
    courtDivisionName: 'Twin Falls',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '091',
    groupDesignator: 'BU',
    courtId: '0209',
    officeName: '',
    officeCode: '1',
    state: 'NY',
    courtName: 'Western District of New York',
    courtDivisionName: 'Buffalo',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '482',
    groupDesignator: 'CB',
    courtId: '0648',
    officeName: '',
    officeCode: '2',
    state: 'OH',
    courtName: 'Southern District of Ohio',
    courtDivisionName: 'Columbus',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '483',
    groupDesignator: 'CB',
    courtId: '0648',
    officeName: '',
    officeCode: '3',
    state: 'OH',
    courtName: 'Southern District of Ohio',
    courtDivisionName: 'Dayton',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '411',
    groupDesignator: 'CC',
    courtId: '0541',
    officeName: '',
    officeCode: '1',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'Brownsville',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '412',
    groupDesignator: 'CC',
    courtId: '0541',
    officeName: '',
    officeCode: '2',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'Corpus Christi',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '415',
    groupDesignator: 'CC',
    courtId: '0541',
    officeName: '',
    officeCode: '5',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'Laredo',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '417',
    groupDesignator: 'CC',
    courtId: '0541',
    officeName: '',
    officeCode: '7',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'McAllen',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '521',
    groupDesignator: 'CH',
    courtId: '0752',
    officeName: '',
    officeCode: '1',
    state: 'IL',
    courtName: 'Northern District of Illinois',
    courtDivisionName: 'Eastern Division',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '523',
    groupDesignator: 'CH',
    courtId: '0752',
    officeName: '',
    officeCode: '3',
    state: 'IL',
    courtName: 'Northern District of Illinois',
    courtDivisionName: 'Western Division',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '481',
    groupDesignator: 'CI',
    courtId: '0648',
    officeName: '',
    officeCode: '1',
    state: 'OH',
    courtName: 'Southern District of Ohio',
    courtDivisionName: 'Cincinnati',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '471',
    groupDesignator: 'CL',
    courtId: '0647',
    officeName: '',
    officeCode: '1',
    state: 'OH',
    courtName: 'Northern District of Ohio',
    courtDivisionName: 'Cleveland',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '473',
    groupDesignator: 'CL',
    courtId: '0647',
    officeName: '',
    officeCode: '3',
    state: 'OH',
    courtName: 'Northern District of Ohio',
    courtDivisionName: 'Toledo',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '474',
    groupDesignator: 'CL',
    courtId: '0647',
    officeName: '',
    officeCode: '4',
    state: 'OH',
    courtName: 'Northern District of Ohio',
    courtDivisionName: 'Youngstown',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '475',
    groupDesignator: 'CL',
    courtId: '0647',
    officeName: '',
    officeCode: '5',
    state: 'OH',
    courtName: 'Northern District of Ohio',
    courtDivisionName: 'Akron',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '476',
    groupDesignator: 'CL',
    courtId: '0647',
    officeName: '',
    officeCode: '6',
    state: 'OH',
    courtName: 'Northern District of Ohio',
    courtDivisionName: 'Canton',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '491',
    groupDesignator: 'CN',
    courtId: '0649',
    officeName: '',
    officeCode: '1',
    state: 'TN',
    courtName: 'Eastern District of Tennessee',
    courtDivisionName: 'Chattanooga',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '492',
    groupDesignator: 'CN',
    courtId: '0649',
    officeName: '',
    officeCode: '2',
    state: 'TN',
    courtName: 'Eastern District of Tennessee',
    courtDivisionName: 'Greeneville',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '493',
    groupDesignator: 'CN',
    courtId: '0649',
    officeName: '',
    officeCode: '3',
    state: 'TN',
    courtName: 'Eastern District of Tennessee',
    courtDivisionName: 'Knoxville',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '494',
    groupDesignator: 'CN',
    courtId: '0649',
    officeName: '',
    officeCode: '4',
    state: 'TN',
    courtName: 'Eastern District of Tennessee',
    courtDivisionName: 'Winchester',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '495',
    groupDesignator: 'CN',
    courtId: '0649',
    officeName: '',
    officeCode: '5',
    state: 'TN',
    courtName: 'Eastern District of Tennessee',
    courtDivisionName: 'Johnson City',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '202',
    groupDesignator: 'CO',
    courtId: '0420',
    officeName: '',
    officeCode: '2',
    state: 'SC',
    courtName: 'District of South Carolina',
    courtDivisionName: 'Charleston',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '203',
    groupDesignator: 'CO',
    courtId: '0420',
    officeName: '',
    officeCode: '3',
    state: 'SC',
    courtName: 'District of South Carolina',
    courtDivisionName: 'Columbia',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '206',
    groupDesignator: 'CO',
    courtId: '0420',
    officeName: '',
    officeCode: '6',
    state: 'SC',
    courtName: 'District of South Carolina',
    courtDivisionName: 'Greenville',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '207',
    groupDesignator: 'CO',
    courtId: '0420',
    officeName: '',
    officeCode: '7',
    state: 'SC',
    courtName: 'District of South Carolina',
    courtDivisionName: 'Spartanburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '621',
    groupDesignator: 'CR',
    courtId: '0862',
    officeName: '',
    officeCode: '1',
    state: 'IA',
    courtName: 'Northern District of Iowa',
    courtDivisionName: 'Cedar Rapids',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '622',
    groupDesignator: 'CR',
    courtId: '0862',
    officeName: '',
    officeCode: '2',
    state: 'IA',
    courtName: 'Northern District of Iowa',
    courtDivisionName: 'Dubuque',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '623',
    groupDesignator: 'CR',
    courtId: '0862',
    officeName: '',
    officeCode: '3',
    state: 'IA',
    courtName: 'Northern District of Iowa',
    courtDivisionName: 'Fort Dodge',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '624',
    groupDesignator: 'CR',
    courtId: '0862',
    officeName: '',
    officeCode: '4',
    state: 'IA',
    courtName: 'Northern District of Iowa',
    courtDivisionName: 'Mason City',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '625',
    groupDesignator: 'CR',
    courtId: '0862',
    officeName: '',
    officeCode: '5',
    state: 'IA',
    courtName: 'Northern District of Iowa',
    courtDivisionName: 'Sioux City',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '626',
    groupDesignator: 'CR',
    courtId: '0862',
    officeName: '',
    officeCode: '6',
    state: 'IA',
    courtName: 'Northern District of Iowa',
    courtDivisionName: 'Waterloo',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '241',
    groupDesignator: 'CT',
    courtId: '0424',
    officeName: '',
    officeCode: '1',
    state: 'WV',
    courtName: 'Northern District of West Virginia',
    courtDivisionName: 'Clarksburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '251',
    groupDesignator: 'CT',
    courtId: '0425',
    officeName: '',
    officeCode: '1',
    state: 'WV',
    courtName: 'Southern District of West Virginia',
    courtDivisionName: 'Bluefield',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '252',
    groupDesignator: 'CT',
    courtId: '0425',
    officeName: '',
    officeCode: '2',
    state: 'WV',
    courtName: 'Southern District of West Virginia',
    courtDivisionName: 'Charleston',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '242',
    groupDesignator: 'CT',
    courtId: '0424',
    officeName: '',
    officeCode: '2',
    state: 'WV',
    courtName: 'Northern District of West Virginia',
    courtDivisionName: 'Elkins',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '243',
    groupDesignator: 'CT',
    courtId: '0424',
    officeName: '',
    officeCode: '3',
    state: 'WV',
    courtName: 'Northern District of West Virginia',
    courtDivisionName: 'Martinsburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '253',
    groupDesignator: 'CT',
    courtId: '0425',
    officeName: '',
    officeCode: '3',
    state: 'WV',
    courtName: 'Southern District of West Virginia',
    courtDivisionName: 'Huntington',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '254',
    groupDesignator: 'CT',
    courtId: '0425',
    officeName: '',
    officeCode: '4',
    state: 'WV',
    courtName: 'Southern District of West Virginia',
    courtDivisionName: '(do not select) Parkersburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '255',
    groupDesignator: 'CT',
    courtId: '0425',
    officeName: '',
    officeCode: '5',
    state: 'WV',
    courtName: 'Southern District of West Virginia',
    courtDivisionName: 'Beckley',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '245',
    groupDesignator: 'CT',
    courtId: '0424',
    officeName: '',
    officeCode: '5',
    state: 'WV',
    courtName: 'Northern District of West Virginia',
    courtDivisionName: 'Wheeling',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '256',
    groupDesignator: 'CT',
    courtId: '0425',
    officeName: '',
    officeCode: '6',
    state: 'WV',
    courtName: 'Southern District of West Virginia',
    courtDivisionName: 'Parkersburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '891',
    groupDesignator: 'CY',
    courtId: '1089',
    officeName: '',
    officeCode: '1',
    state: 'WY',
    courtName: 'District of Wyoming',
    courtDivisionName: 'Casper',
    regionId: '19',
    regionName: 'DENVER',
  },
  {
    courtDivisionCode: '892',
    groupDesignator: 'CY',
    courtId: '1089',
    officeName: '',
    officeCode: '2',
    state: 'WY',
    courtName: 'District of Wyoming',
    courtDivisionName: 'Cheyenne',
    regionId: '19',
    regionName: 'DENVER',
  },
  {
    courtDivisionCode: '391',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '1',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Abilene',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '392',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '2',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Amarillo',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '393',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '3',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Dallas',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '394',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '4',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Ft. Worth',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '395',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '5',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Lubbock',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '396',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '6',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'San Angelo',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '397',
    groupDesignator: 'DA',
    courtId: '0539',
    officeName: '',
    officeCode: '7',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Wichita Falls',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '451',
    groupDesignator: 'DE',
    courtId: '0645',
    officeName: '',
    officeCode: '1',
    state: 'MI',
    courtName: 'Eastern District of Michigan',
    courtDivisionName: 'Bay City',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '452',
    groupDesignator: 'DE',
    courtId: '0645',
    officeName: '',
    officeCode: '2',
    state: 'MI',
    courtName: 'Eastern District of Michigan',
    courtDivisionName: 'Detroit',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '454',
    groupDesignator: 'DE',
    courtId: '0645',
    officeName: '',
    officeCode: '4',
    state: 'MI',
    courtName: 'Eastern District of Michigan',
    courtDivisionName: 'Flint',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '631',
    groupDesignator: 'DM',
    courtId: '0863',
    officeName: '',
    officeCode: '1',
    state: 'IA',
    courtName: 'Southern District of Iowa',
    courtDivisionName: 'Council Bluffs',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '633',
    groupDesignator: 'DM',
    courtId: '0863',
    officeName: '',
    officeCode: '3',
    state: 'IA',
    courtName: 'Southern District of Iowa',
    courtDivisionName: 'Davenport',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '634',
    groupDesignator: 'DM',
    courtId: '0863',
    officeName: '',
    officeCode: '4',
    state: 'IA',
    courtName: 'Southern District of Iowa',
    courtDivisionName: 'Des Moines',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '821',
    groupDesignator: 'DV',
    courtId: '1082',
    officeName: '',
    officeCode: '1',
    state: 'CO',
    courtName: 'District of Colorado',
    courtDivisionName: 'Denver',
    regionId: '19',
    regionName: 'DENVER',
  },
  {
    courtDivisionCode: '796',
    groupDesignator: 'EG',
    courtId: '0979',
    officeName: '',
    officeCode: '6',
    state: 'OR',
    courtName: 'District of Oregon',
    courtDivisionName: 'Eugene',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '721',
    groupDesignator: 'FR',
    courtId: '0972',
    officeName: '',
    officeCode: '1',
    state: 'CA',
    courtName: 'Eastern District of California',
    courtDivisionName: 'Fresno',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '771',
    groupDesignator: 'GF',
    courtId: '0977',
    officeName: '',
    officeCode: '1',
    state: 'MT',
    courtName: 'District of Montana',
    courtDivisionName: 'BIL',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '772',
    groupDesignator: 'GF',
    courtId: '0977',
    officeName: '',
    officeCode: '2',
    state: 'MT',
    courtName: 'District of Montana',
    courtDivisionName: 'Butte',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '774',
    groupDesignator: 'GF',
    courtId: '0977',
    officeName: '',
    officeCode: '4',
    state: 'MT',
    courtName: 'District of Montana',
    courtDivisionName: 'GTF',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '779',
    groupDesignator: 'GF',
    courtId: '0977',
    officeName: '',
    officeCode: '9',
    state: 'MT',
    courtName: 'District of Montana',
    courtDivisionName: 'MSO',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '461',
    groupDesignator: 'GR',
    courtId: '0646',
    officeName: '',
    officeCode: '1',
    state: 'MI',
    courtName: 'Western District of Michigan',
    courtDivisionName: 'Grand Rapids',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '462',
    groupDesignator: 'GR',
    courtId: '0646',
    officeName: '',
    officeCode: '2',
    state: 'MI',
    courtName: 'Western District of Michigan',
    courtDivisionName: 'Marquette',
    regionId: '09',
    regionName: 'CLEVELAND',
  },
  {
    courtDivisionCode: '141',
    groupDesignator: 'HA',
    courtId: '0314',
    officeName: '',
    officeCode: '1',
    state: 'PA',
    courtName: 'Middle District of Pennsylvania',
    courtDivisionName: 'Harrisburg',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '144',
    groupDesignator: 'HA',
    courtId: '0314',
    officeName: '',
    officeCode: '4',
    state: 'PA',
    courtName: 'Middle District of Pennsylvania',
    courtDivisionName: 'Williamsport',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '145',
    groupDesignator: 'HA',
    courtId: '0314',
    officeName: '',
    officeCode: '5',
    state: 'PA',
    courtName: 'Middle District of Pennsylvania',
    courtDivisionName: 'Wilkes-Barre',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '751',
    groupDesignator: 'HI',
    courtId: '0975',
    officeName: '',
    officeCode: '1',
    state: 'HI',
    courtName: 'District of Hawaii',
    courtDivisionName: 'Honolulu',
    regionId: '15',
    regionName: 'SAN DIEGO',
  },
  {
    courtDivisionCode: '931',
    groupDesignator: 'HI',
    courtId: '0993',
    officeName: '',
    officeCode: '1',
    state: 'GU',
    courtName: 'District of Guam',
    courtDivisionName: 'Hagatna',
    regionId: '15',
    regionName: 'SAN DIEGO',
  },
  {
    courtDivisionCode: '941',
    groupDesignator: 'HI',
    courtId: '0994',
    officeName: '',
    officeCode: '1',
    state: 'MP',
    courtName: 'District of Northern Marianas',
    courtDivisionName: 'Northern Mariana Islands',
    regionId: '15',
    regionName: 'SAN DIEGO',
  },
  {
    courtDivisionCode: '042',
    groupDesignator: 'HR',
    courtId: '0104',
    officeName: '',
    officeCode: '2',
    state: 'PR',
    courtName: 'District of Puerto Rico',
    courtDivisionName: 'Ponce',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '043',
    groupDesignator: 'HR',
    courtId: '0104',
    officeName: '',
    officeCode: '3',
    state: 'PR',
    courtName: 'District of Puerto Rico',
    courtDivisionName: 'Old San Juan',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '413',
    groupDesignator: 'HU',
    courtId: '0541',
    officeName: '',
    officeCode: '3',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'Galveston',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '414',
    groupDesignator: 'HU',
    courtId: '0541',
    officeName: '',
    officeCode: '4',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'Houston',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '416',
    groupDesignator: 'HU',
    courtId: '0541',
    officeName: '',
    officeCode: '6',
    state: 'TX',
    courtName: 'Southern District of Texas',
    courtDivisionName: 'Victoria',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '561',
    groupDesignator: 'IN',
    courtId: '0756',
    officeName: '',
    officeCode: '1',
    state: 'IN',
    courtName: 'Southern District of Indiana',
    courtDivisionName: 'Indianapolis',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '562',
    groupDesignator: 'IN',
    courtId: '0756',
    officeName: '',
    officeCode: '2',
    state: 'IN',
    courtName: 'Southern District of Indiana',
    courtDivisionName: 'Terre Haute',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '563',
    groupDesignator: 'IN',
    courtId: '0756',
    officeName: '',
    officeCode: '3',
    state: 'IN',
    courtName: 'Southern District of Indiana',
    courtDivisionName: 'Evansville',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '564',
    groupDesignator: 'IN',
    courtId: '0756',
    officeName: '',
    officeCode: '4',
    state: 'IN',
    courtName: 'Southern District of Indiana',
    courtDivisionName: 'New Albany',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '371',
    groupDesignator: 'JA',
    courtId: '0537',
    officeName: '',
    officeCode: '1',
    state: 'MS',
    courtName: 'Northern District of Mississippi',
    courtDivisionName: 'Aberdeen',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '381',
    groupDesignator: 'JA',
    courtId: '0538',
    officeName: '',
    officeCode: '1',
    state: 'MS',
    courtName: 'Southern District of Mississippi',
    courtDivisionName: 'Gulfport-1 Divisional Office',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '383',
    groupDesignator: 'JA',
    courtId: '0538',
    officeName: '',
    officeCode: '3',
    state: 'MS',
    courtName: 'Southern District of Mississippi',
    courtDivisionName: 'Jackson-3 Divisional Office',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '386',
    groupDesignator: 'JA',
    courtId: '0538',
    officeName: '',
    officeCode: '6',
    state: 'MS',
    courtName: 'Southern District of Mississippi',
    courtDivisionName: 'Gulfport-6 Divisional Office',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '662',
    groupDesignator: 'KC',
    courtId: '0866',
    officeName: '',
    officeCode: '2',
    state: 'MO',
    courtName: 'Western District of Missouri',
    courtDivisionName: 'Jefferson City',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '663',
    groupDesignator: 'KC',
    courtId: '0866',
    officeName: '',
    officeCode: '3',
    state: 'MO',
    courtName: 'Western District of Missouri',
    courtDivisionName: 'Joplin',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '664',
    groupDesignator: 'KC',
    courtId: '0866',
    officeName: '',
    officeCode: '4',
    state: 'MO',
    courtName: 'Western District of Missouri',
    courtDivisionName: 'Kansas City',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '665',
    groupDesignator: 'KC',
    courtId: '0866',
    officeName: '',
    officeCode: '5',
    state: 'MO',
    courtName: 'Western District of Missouri',
    courtDivisionName: 'St. Joseph',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '666',
    groupDesignator: 'KC',
    courtId: '0866',
    officeName: '',
    officeCode: '6',
    state: 'MO',
    courtName: 'Western District of Missouri',
    courtDivisionName: 'Springfield',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '732',
    groupDesignator: 'LA',
    courtId: '0973',
    officeName: '',
    officeCode: '2',
    state: 'CA',
    courtName: 'Central District of California',
    courtDivisionName: 'Los Angeles',
    regionId: '16',
    regionName: 'LOS ANGELES',
  },
  {
    courtDivisionCode: '070',
    groupDesignator: 'LI',
    courtId: '0207',
    officeName: '',
    officeCode: '0',
    state: 'NY',
    courtName: 'Eastern District of New York',
    courtDivisionName: 'Islip',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '078',
    groupDesignator: 'LI',
    courtId: '0207',
    officeName: '',
    officeCode: '8',
    state: 'NY',
    courtName: 'Eastern District of New York',
    courtDivisionName: 'Central Islip',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '441',
    groupDesignator: 'LO',
    courtId: '0644',
    officeName: '',
    officeCode: '1',
    state: 'KY',
    courtName: 'Western District of Kentucky',
    courtDivisionName: 'Bowling Green',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '443',
    groupDesignator: 'LO',
    courtId: '0644',
    officeName: '',
    officeCode: '3',
    state: 'KY',
    courtName: 'Western District of Kentucky',
    courtDivisionName: 'Louisville',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '444',
    groupDesignator: 'LO',
    courtId: '0644',
    officeName: '',
    officeCode: '4',
    state: 'KY',
    courtName: 'Western District of Kentucky',
    courtDivisionName: 'Owensboro',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '445',
    groupDesignator: 'LO',
    courtId: '0644',
    officeName: '',
    officeCode: '5',
    state: 'KY',
    courtName: 'Western District of Kentucky',
    courtDivisionName: 'Paducah',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '611',
    groupDesignator: 'LR',
    courtId: '0861',
    officeName: '',
    officeCode: '1',
    state: 'AR',
    courtName: 'Western District of Arkansas',
    courtDivisionName: 'El Dorado',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '601',
    groupDesignator: 'LR',
    courtId: '0860',
    officeName: '',
    officeCode: '1',
    state: 'AR',
    courtName: 'Eastern District of Arkansas',
    courtDivisionName: 'Batesville',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '602',
    groupDesignator: 'LR',
    courtId: '0860',
    officeName: '',
    officeCode: '2',
    state: 'AR',
    courtName: 'Eastern District of Arkansas',
    courtDivisionName: 'Delta Division',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '612',
    groupDesignator: 'LR',
    courtId: '0861',
    officeName: '',
    officeCode: '2',
    state: 'AR',
    courtName: 'Western District of Arkansas',
    courtDivisionName: 'Fort Smith',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '613',
    groupDesignator: 'LR',
    courtId: '0861',
    officeName: '',
    officeCode: '3',
    state: 'AR',
    courtName: 'Western District of Arkansas',
    courtDivisionName: 'Harrison',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '603',
    groupDesignator: 'LR',
    courtId: '0860',
    officeName: '',
    officeCode: '3',
    state: 'AR',
    courtName: 'Eastern District of Arkansas',
    courtDivisionName: 'Northern Division',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '604',
    groupDesignator: 'LR',
    courtId: '0860',
    officeName: '',
    officeCode: '4',
    state: 'AR',
    courtName: 'Eastern District of Arkansas',
    courtDivisionName: 'Central Division',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '614',
    groupDesignator: 'LR',
    courtId: '0861',
    officeName: '',
    officeCode: '4',
    state: 'AR',
    courtName: 'Western District of Arkansas',
    courtDivisionName: 'Texarkana',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '615',
    groupDesignator: 'LR',
    courtId: '0861',
    officeName: '',
    officeCode: '5',
    state: 'AR',
    courtName: 'Western District of Arkansas',
    courtDivisionName: 'Fayetteville',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '605',
    groupDesignator: 'LR',
    courtId: '0860',
    officeName: '',
    officeCode: '5',
    state: 'AR',
    courtName: 'Eastern District of Arkansas',
    courtDivisionName: 'Pine Bluff',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '616',
    groupDesignator: 'LR',
    courtId: '0861',
    officeName: '',
    officeCode: '6',
    state: 'AR',
    courtName: 'Western District of Arkansas',
    courtDivisionName: 'Hot Springs',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '782',
    groupDesignator: 'LV',
    courtId: '0978',
    officeName: '',
    officeCode: '2',
    state: 'NV',
    courtName: 'District of Nevada',
    courtDivisionName: 'Las Vegas',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '431',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '1',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'Ashland',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '432',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '2',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'Covington',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '433',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '3',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'Frankfort',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '435',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '5',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'Lexington',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '436',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '6',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'London',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '437',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '7',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'Pikeville',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '439',
    groupDesignator: 'LX',
    courtId: '0643',
    officeName: '',
    officeCode: '9',
    state: 'KY',
    courtName: 'Eastern District of Kentucky',
    courtDivisionName: 'Test Division',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '331',
    groupDesignator: 'MC',
    courtId: '113G',
    officeName: '',
    officeCode: '1',
    state: 'GA',
    courtName: 'Middle District of Georgia',
    courtDivisionName: 'Albany',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '333',
    groupDesignator: 'MC',
    courtId: '113G',
    officeName: '',
    officeCode: '3',
    state: 'GA',
    courtName: 'Middle District of Georgia',
    courtDivisionName: 'Athens',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '334',
    groupDesignator: 'MC',
    courtId: '113G',
    officeName: '',
    officeCode: '4',
    state: 'GA',
    courtName: 'Middle District of Georgia',
    courtDivisionName: 'Columbus',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '335',
    groupDesignator: 'MC',
    courtId: '113G',
    officeName: '',
    officeCode: '5',
    state: 'GA',
    courtName: 'Middle District of Georgia',
    courtDivisionName: 'Macon',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '336',
    groupDesignator: 'MC',
    courtId: '113G',
    officeName: '',
    officeCode: '6',
    state: 'GA',
    courtName: 'Middle District of Georgia',
    courtDivisionName: 'Thomasville',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '337',
    groupDesignator: 'MC',
    courtId: '113G',
    officeName: '',
    officeCode: '7',
    state: 'GA',
    courtName: 'Middle District of Georgia',
    courtDivisionName: 'Valdosta',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '581',
    groupDesignator: 'MD',
    courtId: '0758',
    officeName: '',
    officeCode: '1',
    state: 'WI',
    courtName: 'Western District of Wisconsin',
    courtDivisionName: 'Eau Claire',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '582',
    groupDesignator: 'MD',
    courtId: '0758',
    officeName: '',
    officeCode: '2',
    state: 'WI',
    courtName: 'Western District of Wisconsin',
    courtDivisionName: 'La Crosse',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '583',
    groupDesignator: 'MD',
    courtId: '0758',
    officeName: '',
    officeCode: '3',
    state: 'WI',
    courtName: 'Western District of Wisconsin',
    courtDivisionName: 'Madison',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '585',
    groupDesignator: 'MD',
    courtId: '0758',
    officeName: '',
    officeCode: '5',
    state: 'WI',
    courtName: 'Western District of Wisconsin',
    courtDivisionName: 'Wausau',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '586',
    groupDesignator: 'MD',
    courtId: '0758',
    officeName: '',
    officeCode: '6',
    state: 'WI',
    courtName: 'Western District of Wisconsin',
    courtDivisionName: 'Superior',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '511',
    groupDesignator: 'ME',
    courtId: '0651',
    officeName: '',
    officeCode: '1',
    state: 'TN',
    courtName: 'Western District of Tennessee',
    courtDivisionName: 'Jackson',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '512',
    groupDesignator: 'ME',
    courtId: '0651',
    officeName: '',
    officeCode: '2',
    state: 'TN',
    courtName: 'Western District of Tennessee',
    courtDivisionName: 'Memphis',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '572',
    groupDesignator: 'MI',
    courtId: '0757',
    officeName: '',
    officeCode: '2',
    state: 'WI',
    courtName: 'Eastern District of Wisconsin',
    courtDivisionName: 'Milwaukee',
    regionId: '11',
    regionName: 'CHICAGO',
  },
  {
    courtDivisionCode: '320',
    groupDesignator: 'MM',
    courtId: '113C',
    officeName: '',
    officeCode: '0',
    state: 'FL',
    courtName: 'Southern District of Florida',
    courtDivisionName: 'Fort Lauderdale',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '321',
    groupDesignator: 'MM',
    courtId: '113C',
    officeName: '',
    officeCode: '1',
    state: 'FL',
    courtName: 'Southern District of Florida',
    courtDivisionName: 'Miami',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '329',
    groupDesignator: 'MM',
    courtId: '113C',
    officeName: '',
    officeCode: '9',
    state: 'FL',
    courtName: 'Southern District of Florida',
    courtDivisionName: 'West Palm Beach',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '643',
    groupDesignator: 'MN',
    courtId: '0864',
    officeName: '',
    officeCode: '3',
    state: 'MN',
    courtName: 'District of Minnesota',
    courtDivisionName: 'St Paul',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '644',
    groupDesignator: 'MN',
    courtId: '0864',
    officeName: '',
    officeCode: '4',
    state: 'MN',
    courtName: 'District of Minnesota',
    courtDivisionName: 'Minneapolis',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '645',
    groupDesignator: 'MN',
    courtId: '0864',
    officeName: '',
    officeCode: '5',
    state: 'MN',
    courtName: 'District of Minnesota',
    courtDivisionName: 'Duluth',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '646',
    groupDesignator: 'MN',
    courtId: '0864',
    officeName: '',
    officeCode: '6',
    state: 'MN',
    courtName: 'District of Minnesota',
    courtDivisionName: 'Fergus Falls',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '021',
    groupDesignator: 'MR',
    courtId: '0102',
    officeName: '',
    officeCode: '1',
    state: 'NH',
    courtName: 'District of New Hampshire',
    courtDivisionName: 'Concord',
    regionId: '01',
    regionName: 'BOSTON',
  },
  {
    courtDivisionCode: '501',
    groupDesignator: 'NA',
    courtId: '0650',
    officeName: '',
    officeCode: '1',
    state: 'TN',
    courtName: 'Middle District of Tennessee',
    courtDivisionName: 'Columbia',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '502',
    groupDesignator: 'NA',
    courtId: '0650',
    officeName: '',
    officeCode: '2',
    state: 'TN',
    courtName: 'Middle District of Tennessee',
    courtDivisionName: 'Cookeville',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '503',
    groupDesignator: 'NA',
    courtId: '0650',
    officeName: '',
    officeCode: '3',
    state: 'TN',
    courtName: 'Middle District of Tennessee',
    courtDivisionName: 'Nashville',
    regionId: '08',
    regionName: 'MEMPHIS',
  },
  {
    courtDivisionCode: '121',
    groupDesignator: 'NE',
    courtId: '0312',
    officeName: '',
    officeCode: '1',
    state: 'NJ',
    courtName: 'District of New Jersey',
    courtDivisionName: 'Camden',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '122',
    groupDesignator: 'NE',
    courtId: '0312',
    officeName: '',
    officeCode: '2',
    state: 'NJ',
    courtName: 'District of New Jersey',
    courtDivisionName: 'Newark',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '123',
    groupDesignator: 'NE',
    courtId: '0312',
    officeName: '',
    officeCode: '3',
    state: 'NJ',
    courtName: 'District of New Jersey',
    courtDivisionName: 'Trenton',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '052',
    groupDesignator: 'NH',
    courtId: '0205',
    officeName: '',
    officeCode: '2',
    state: 'CT',
    courtName: 'District of Connecticut',
    courtDivisionName: 'Hartford',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '053',
    groupDesignator: 'NH',
    courtId: '0205',
    officeName: '',
    officeCode: '3',
    state: 'CT',
    courtName: 'District of Connecticut',
    courtDivisionName: 'New Haven',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '055',
    groupDesignator: 'NH',
    courtId: '0205',
    officeName: '',
    officeCode: '5',
    state: 'CT',
    courtName: 'District of Connecticut',
    courtDivisionName: 'Bridgeport',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '222',
    groupDesignator: 'NO',
    courtId: '0422',
    officeName: '',
    officeCode: '2',
    state: 'VA',
    courtName: 'Eastern District of Virginia',
    courtDivisionName: 'Norfolk',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '224',
    groupDesignator: 'NO',
    courtId: '0422',
    officeName: '',
    officeCode: '4',
    state: 'VA',
    courtName: 'Eastern District of Virginia',
    courtDivisionName: 'Newport News',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '3L2',
    groupDesignator: 'NR',
    courtId: '053L',
    officeName: '',
    officeCode: '2',
    state: 'LA',
    courtName: 'Eastern District of Louisiana',
    courtDivisionName: 'New Orleans',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '3N3',
    groupDesignator: 'NR',
    courtId: '053N',
    officeName: '',
    officeCode: '3',
    state: 'LA',
    courtName: 'Middle District of Louisiana',
    courtDivisionName: 'Baton Rouge',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '3N4',
    groupDesignator: 'NR',
    courtId: '053N',
    officeName: '',
    officeCode: '4',
    state: 'LA',
    courtName: 'Middle District of Louisiana',
    courtDivisionName: 'Opelousas',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '081',
    groupDesignator: 'NY',
    courtId: '0208',
    officeName: '',
    officeCode: '1',
    state: 'NY',
    courtName: 'Southern District of New York',
    courtDivisionName: 'Manhattan',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '087',
    groupDesignator: 'NY',
    courtId: '0208',
    officeName: '',
    officeCode: '7',
    state: 'NY',
    courtName: 'Southern District of New York',
    courtDivisionName: 'White Plains',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '714',
    groupDesignator: 'OA',
    courtId: '0971',
    officeName: '',
    officeCode: '4',
    state: 'CA',
    courtName: 'Northern District of California',
    courtDivisionName: 'Oakland',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '875',
    groupDesignator: 'OC',
    courtId: '1087',
    officeName: '',
    officeCode: '5',
    state: 'OK',
    courtName: 'Western District of Oklahoma',
    courtDivisionName: 'Oklahoma City',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '674',
    groupDesignator: 'OM',
    courtId: '0867',
    officeName: '',
    officeCode: '4',
    state: 'NE',
    courtName: 'District of Nebraska',
    courtDivisionName: 'Lincoln Office',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '678',
    groupDesignator: 'OM',
    courtId: '0867',
    officeName: '',
    officeCode: '8',
    state: 'NE',
    courtName: 'District of Nebraska',
    courtDivisionName: 'Omaha Office',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '3A3',
    groupDesignator: 'OR',
    courtId: '113A',
    officeName: '',
    officeCode: '3',
    state: 'FL',
    courtName: 'Middle District of Florida',
    courtDivisionName: 'Jacksonville',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3A6',
    groupDesignator: 'OR',
    courtId: '113A',
    officeName: '',
    officeCode: '6',
    state: 'FL',
    courtName: 'Middle District of Florida',
    courtDivisionName: 'Orlando',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '531',
    groupDesignator: 'PE',
    courtId: '0753',
    officeName: '',
    officeCode: '1',
    state: 'IL',
    courtName: 'Central District of Illinois',
    courtDivisionName: 'Peoria',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '532',
    groupDesignator: 'PE',
    courtId: '0753',
    officeName: '',
    officeCode: '2',
    state: 'IL',
    courtName: 'Central District of Illinois',
    courtDivisionName: 'Urbana',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '533',
    groupDesignator: 'PE',
    courtId: '0753',
    officeName: '',
    officeCode: '3',
    state: 'IL',
    courtName: 'Central District of Illinois',
    courtDivisionName: 'Springfield',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '543',
    groupDesignator: 'PE',
    courtId: '0754',
    officeName: '',
    officeCode: '3',
    state: 'IL',
    courtName: 'Southern District of Illinois',
    courtDivisionName: 'East St Louis',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '544',
    groupDesignator: 'PE',
    courtId: '0754',
    officeName: '',
    officeCode: '4',
    state: 'IL',
    courtName: 'Southern District of Illinois',
    courtDivisionName: 'Benton',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '545',
    groupDesignator: 'PE',
    courtId: '0754',
    officeName: '',
    officeCode: '5',
    state: 'IL',
    courtName: 'Southern District of Illinois',
    courtDivisionName: 'Alton',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '546',
    groupDesignator: 'PE',
    courtId: '0754',
    officeName: '',
    officeCode: '6',
    state: 'IL',
    courtName: 'Southern District of Illinois',
    courtDivisionName: 'Effingham',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '131',
    groupDesignator: 'PH',
    courtId: '0313',
    officeName: '',
    officeCode: '1',
    state: 'PA',
    courtName: 'Eastern District of Pennsylvania',
    courtDivisionName: 'X',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '132',
    groupDesignator: 'PH',
    courtId: '0313',
    officeName: '',
    officeCode: '2',
    state: 'PA',
    courtName: 'Eastern District of Pennsylvania',
    courtDivisionName: 'Philadelphia',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '133',
    groupDesignator: 'PH',
    courtId: '0313',
    officeName: '',
    officeCode: '3',
    state: 'PA',
    courtName: 'Eastern District of Pennsylvania',
    courtDivisionName: 'XXX',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '134',
    groupDesignator: 'PH',
    courtId: '0313',
    officeName: '',
    officeCode: '4',
    state: 'PA',
    courtName: 'Eastern District of Pennsylvania',
    courtDivisionName: 'Reading',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '151',
    groupDesignator: 'PI',
    courtId: '0315',
    officeName: '',
    officeCode: '1',
    state: 'PA',
    courtName: 'Western District of Pennsylvania',
    courtDivisionName: 'Erie',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '152',
    groupDesignator: 'PI',
    courtId: '0315',
    officeName: '',
    officeCode: '2',
    state: 'PA',
    courtName: 'Western District of Pennsylvania',
    courtDivisionName: 'Pittsburgh',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '153',
    groupDesignator: 'PI',
    courtId: '0315',
    officeName: '',
    officeCode: '3',
    state: 'PA',
    courtName: 'Western District of Pennsylvania',
    courtDivisionName: 'XXX',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '154',
    groupDesignator: 'PI',
    courtId: '0315',
    officeName: '',
    officeCode: '4',
    state: 'PA',
    courtName: 'Western District of Pennsylvania',
    courtDivisionName: 'IV',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '157',
    groupDesignator: 'PI',
    courtId: '0315',
    officeName: '',
    officeCode: '7',
    state: 'PA',
    courtName: 'Western District of Pennsylvania',
    courtDivisionName: 'Johnstown',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '793',
    groupDesignator: 'PL',
    courtId: '0979',
    officeName: '',
    officeCode: '3',
    state: 'OR',
    courtName: 'District of Oregon',
    courtDivisionName: 'Portland',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '001',
    groupDesignator: 'PO',
    courtId: '0100',
    officeName: '',
    officeCode: '1',
    state: 'ME',
    courtName: 'District of Maine',
    courtDivisionName: 'Bangor',
    regionId: '01',
    regionName: 'BOSTON',
  },
  {
    courtDivisionCode: '002',
    groupDesignator: 'PO',
    courtId: '0100',
    officeName: '',
    officeCode: '2',
    state: 'ME',
    courtName: 'District of Maine',
    courtDivisionName: 'Portland',
    regionId: '01',
    regionName: 'BOSTON',
  },
  {
    courtDivisionCode: '031',
    groupDesignator: 'PR',
    courtId: '0103',
    officeName: '',
    officeCode: '1',
    state: 'RI',
    courtName: 'District of Rhode Island',
    courtDivisionName: 'Providence',
    regionId: '01',
    regionName: 'BOSTON',
  },
  {
    courtDivisionCode: '700',
    groupDesignator: 'PX',
    courtId: '0970',
    officeName: '',
    officeCode: '0',
    state: 'AZ',
    courtName: 'District of Arizona',
    courtDivisionName: 'Yuma',
    regionId: '14',
    regionName: 'PHOENIX',
  },
  {
    courtDivisionCode: '702',
    groupDesignator: 'PX',
    courtId: '0970',
    officeName: '',
    officeCode: '2',
    state: 'AZ',
    courtName: 'District of Arizona',
    courtDivisionName: 'Phoenix',
    regionId: '14',
    regionName: 'PHOENIX',
  },
  {
    courtDivisionCode: '703',
    groupDesignator: 'PX',
    courtId: '0970',
    officeName: '',
    officeCode: '3',
    state: 'AZ',
    courtName: 'District of Arizona',
    courtDivisionName: 'Prescott',
    regionId: '14',
    regionName: 'PHOENIX',
  },
  {
    courtDivisionCode: '704',
    groupDesignator: 'PX',
    courtId: '0970',
    officeName: '',
    officeCode: '4',
    state: 'AZ',
    courtName: 'District of Arizona',
    courtDivisionName: 'Tucson',
    regionId: '14',
    regionName: 'PHOENIX',
  },
  {
    courtDivisionCode: '783',
    groupDesignator: 'RE',
    courtId: '0978',
    officeName: '',
    officeCode: '3',
    state: 'NV',
    courtName: 'District of Nevada',
    courtDivisionName: 'Reno',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '223',
    groupDesignator: 'RH',
    courtId: '0422',
    officeName: '',
    officeCode: '3',
    state: 'VA',
    courtName: 'Eastern District of Virginia',
    courtDivisionName: 'Richmond',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '160',
    groupDesignator: 'RK',
    courtId: '0416',
    officeName: '',
    officeCode: '0',
    state: 'MD',
    courtName: 'District of Maryland',
    courtDivisionName: 'Greenbelt',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '235',
    groupDesignator: 'RN',
    courtId: '0423',
    officeName: '',
    officeCode: '5',
    state: 'VA',
    courtName: 'Western District of Virginia',
    courtDivisionName: 'Harrisonburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '236',
    groupDesignator: 'RN',
    courtId: '0423',
    officeName: '',
    officeCode: '6',
    state: 'VA',
    courtName: 'Western District of Virginia',
    courtDivisionName: 'Lynchburg',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '237',
    groupDesignator: 'RN',
    courtId: '0423',
    officeName: '',
    officeCode: '7',
    state: 'VA',
    courtName: 'Western District of Virginia',
    courtDivisionName: 'Roanoke',
    regionId: '04',
    regionName: 'COLUMBIA',
  },
  {
    courtDivisionCode: '092',
    groupDesignator: 'RO',
    courtId: '0209',
    officeName: '',
    officeCode: '2',
    state: 'NY',
    courtName: 'Western District of New York',
    courtDivisionName: 'Rochester',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '738',
    groupDesignator: 'SA',
    courtId: '0973',
    officeName: '',
    officeCode: '8',
    state: 'CA',
    courtName: 'Central District of California',
    courtDivisionName: 'Santa Ana',
    regionId: '16',
    regionName: 'LOS ANGELES',
  },
  {
    courtDivisionCode: '736',
    groupDesignator: 'SB',
    courtId: '0973',
    officeName: '',
    officeCode: '6',
    state: 'CA',
    courtName: 'Central District of California',
    courtDivisionName: 'Riverside',
    regionId: '16',
    regionName: 'LOS ANGELES',
  },
  {
    courtDivisionCode: '722',
    groupDesignator: 'SC',
    courtId: '0972',
    officeName: '',
    officeCode: '2',
    state: 'CA',
    courtName: 'Eastern District of California',
    courtDivisionName: 'Sacramento',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '729',
    groupDesignator: 'SC',
    courtId: '0972',
    officeName: '',
    officeCode: '9',
    state: 'CA',
    courtName: 'Eastern District of California',
    courtDivisionName: 'Modesto',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '743',
    groupDesignator: 'SD',
    courtId: '0974',
    officeName: '',
    officeCode: '3',
    state: 'CA',
    courtName: 'Southern District of California',
    courtDivisionName: 'San Diego',
    regionId: '15',
    regionName: 'SAN DIEGO',
  },
  {
    courtDivisionCode: '812',
    groupDesignator: 'SE',
    courtId: '0981',
    officeName: '',
    officeCode: '2',
    state: 'WA',
    courtName: 'Western District of Washington',
    courtDivisionName: 'Seattle',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '813',
    groupDesignator: 'SE',
    courtId: '0981',
    officeName: '',
    officeCode: '3',
    state: 'WA',
    courtName: 'Western District of Washington',
    courtDivisionName: 'Tacoma',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '711',
    groupDesignator: 'SF',
    courtId: '0971',
    officeName: '',
    officeCode: '1',
    state: 'CA',
    courtName: 'Northern District of California',
    courtDivisionName: 'Santa Rosa',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '713',
    groupDesignator: 'SF',
    courtId: '0971',
    officeName: '',
    officeCode: '3',
    state: 'CA',
    courtName: 'Northern District of California',
    courtDivisionName: 'San Francisco',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '361',
    groupDesignator: 'SH',
    courtId: '0536',
    officeName: '',
    officeCode: '1',
    state: 'LA',
    courtName: 'Western District of Louisiana',
    courtDivisionName: 'Alexandria',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '362',
    groupDesignator: 'SH',
    courtId: '0536',
    officeName: '',
    officeCode: '2',
    state: 'LA',
    courtName: 'Western District of Louisiana',
    courtDivisionName: 'Lake Charles',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '363',
    groupDesignator: 'SH',
    courtId: '0536',
    officeName: '',
    officeCode: '3',
    state: 'LA',
    courtName: 'Western District of Louisiana',
    courtDivisionName: 'Monroe',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '364',
    groupDesignator: 'SH',
    courtId: '0536',
    officeName: '',
    officeCode: '4',
    state: 'LA',
    courtName: 'Western District of Louisiana',
    courtDivisionName: 'Lafayette',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '365',
    groupDesignator: 'SH',
    courtId: '0536',
    officeName: '',
    officeCode: '5',
    state: 'LA',
    courtName: 'Western District of Louisiana',
    courtDivisionName: 'Shreveport',
    regionId: '05',
    regionName: 'NEW ORLEANS',
  },
  {
    courtDivisionCode: '715',
    groupDesignator: 'SJ',
    courtId: '0971',
    officeName: '',
    officeCode: '5',
    state: 'CA',
    courtName: 'Northern District of California',
    courtDivisionName: 'San Jose',
    regionId: '17',
    regionName: 'SAN FRANCISCO',
  },
  {
    courtDivisionCode: '882',
    groupDesignator: 'SK',
    courtId: '1088',
    officeName: '',
    officeCode: '2',
    state: 'UT',
    courtName: 'District of Utah',
    courtDivisionName: 'Salt Lake City',
    regionId: '19',
    regionName: 'DENVER',
  },
  {
    courtDivisionCode: '884',
    groupDesignator: 'SK',
    courtId: '1088',
    officeName: '',
    officeCode: '4',
    state: 'UT',
    courtName: 'District of Utah',
    courtDivisionName: 'St. George',
    regionId: '19',
    regionName: 'DENVER',
  },
  {
    courtDivisionCode: '651',
    groupDesignator: 'SL',
    courtId: '0865',
    officeName: '',
    officeCode: '1',
    state: 'MO',
    courtName: 'Eastern District of Missouri',
    courtDivisionName: 'Cape Girardeau',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '652',
    groupDesignator: 'SL',
    courtId: '0865',
    officeName: '',
    officeCode: '2',
    state: 'MO',
    courtName: 'Eastern District of Missouri',
    courtDivisionName: 'Hannibal',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '654',
    groupDesignator: 'SL',
    courtId: '0865',
    officeName: '',
    officeCode: '4',
    state: 'MO',
    courtName: 'Eastern District of Missouri',
    courtDivisionName: 'St. Louis',
    regionId: '13',
    regionName: 'KANSAS CITY',
  },
  {
    courtDivisionCode: '423',
    groupDesignator: 'SN',
    courtId: '0542',
    officeName: '',
    officeCode: '3',
    state: 'TX',
    courtName: 'Western District of Texas',
    courtDivisionName: 'El Paso',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '425',
    groupDesignator: 'SN',
    courtId: '0542',
    officeName: '',
    officeCode: '5',
    state: 'TX',
    courtName: 'Western District of Texas',
    courtDivisionName: 'San Antonio',
    regionId: '07',
    regionName: 'HOUSTON',
  },
  {
    courtDivisionCode: '551',
    groupDesignator: 'SO',
    courtId: '0755',
    officeName: '',
    officeCode: '1',
    state: 'IN',
    courtName: 'Northern District of Indiana',
    courtDivisionName: 'Fort Wayne Division',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '552',
    groupDesignator: 'SO',
    courtId: '0755',
    officeName: '',
    officeCode: '2',
    state: 'IN',
    courtName: 'Northern District of Indiana',
    courtDivisionName: 'Hammond Division',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '553',
    groupDesignator: 'SO',
    courtId: '0755',
    officeName: '',
    officeCode: '3',
    state: 'IN',
    courtName: 'Northern District of Indiana',
    courtDivisionName: 'South Bend Division',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '554',
    groupDesignator: 'SO',
    courtId: '0755',
    officeName: '',
    officeCode: '4',
    state: 'IN',
    courtName: 'Northern District of Indiana',
    courtDivisionName: 'Hammond Division at Lafayette',
    regionId: '10',
    regionName: 'INDIANAPOLIS',
  },
  {
    courtDivisionCode: '801',
    groupDesignator: 'SP',
    courtId: '0980',
    officeName: '',
    officeCode: '1',
    state: 'WA',
    courtName: 'Eastern District of Washington',
    courtDivisionName: 'Spokane',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '802',
    groupDesignator: 'SP',
    courtId: '0980',
    officeName: '',
    officeCode: '2',
    state: 'WA',
    courtName: 'Eastern District of Washington',
    courtDivisionName: 'Spokane/Yakima',
    regionId: '18',
    regionName: 'SEATTLE',
  },
  {
    courtDivisionCode: '341',
    groupDesignator: 'SV',
    courtId: '113J',
    officeName: '',
    officeCode: '1',
    state: 'GA',
    courtName: 'Southern District of Georgia',
    courtDivisionName: 'Augusta',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '342',
    groupDesignator: 'SV',
    courtId: '113J',
    officeName: '',
    officeCode: '2',
    state: 'GA',
    courtName: 'Southern District of Georgia',
    courtDivisionName: 'Brunswick',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '343',
    groupDesignator: 'SV',
    courtId: '113J',
    officeName: '',
    officeCode: '3',
    state: 'GA',
    courtName: 'Southern District of Georgia',
    courtDivisionName: 'Dublin',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '344',
    groupDesignator: 'SV',
    courtId: '113J',
    officeName: '',
    officeCode: '4',
    state: 'GA',
    courtName: 'Southern District of Georgia',
    courtDivisionName: 'Savannah',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '345',
    groupDesignator: 'SV',
    courtId: '113J',
    officeName: '',
    officeCode: '5',
    state: 'GA',
    courtName: 'Southern District of Georgia',
    courtDivisionName: 'Waycross',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '346',
    groupDesignator: 'SV',
    courtId: '113J',
    officeName: '',
    officeCode: '6',
    state: 'GA',
    courtName: 'Southern District of Georgia',
    courtDivisionName: 'Statesboro',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '691',
    groupDesignator: 'SX',
    courtId: '0869',
    officeName: '',
    officeCode: '1',
    state: 'SD',
    courtName: 'District of South Dakota',
    courtDivisionName: 'Northern (Aberdeen)',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '693',
    groupDesignator: 'SX',
    courtId: '0869',
    officeName: '',
    officeCode: '3',
    state: 'SD',
    courtName: 'District of South Dakota',
    courtDivisionName: 'Central (Pierre)',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '683',
    groupDesignator: 'SX',
    courtId: '0868',
    officeName: '',
    officeCode: '3',
    state: 'ND',
    courtName: 'District of North Dakota',
    courtDivisionName: 'Fargo',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '694',
    groupDesignator: 'SX',
    courtId: '0869',
    officeName: '',
    officeCode: '4',
    state: 'SD',
    courtName: 'District of South Dakota',
    courtDivisionName: 'Southern (Sioux Falls)',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '695',
    groupDesignator: 'SX',
    courtId: '0869',
    officeName: '',
    officeCode: '5',
    state: 'SD',
    courtName: 'District of South Dakota',
    courtDivisionName: 'Western (Rapid City)',
    regionId: '12',
    regionName: 'MINNEAPOLIS',
  },
  {
    courtDivisionCode: '990',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '0',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Office 0 - AO-DC',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '991',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '1',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Pleasantville',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '992',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '2',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Dubuque',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '993',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '3',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Office 3 - Baker',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '994',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '4',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Hill',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '995',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '5',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Office 5 - Elgin',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '996',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '6',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Phoenix',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '999',
    groupDesignator: 'TE',
    courtId: '1111',
    officeName: '',
    officeCode: '9',
    state: 'IA',
    courtName: 'District of TEST',
    courtDivisionName: 'Automation',
    regionId: '99',
    regionName: 'TEST',
  },
  {
    courtDivisionCode: '291',
    groupDesignator: 'TL',
    courtId: '1129',
    officeName: '',
    officeCode: '1',
    state: 'FL',
    courtName: 'Northern District of Florida',
    courtDivisionName: 'Gainesville',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '293',
    groupDesignator: 'TL',
    courtId: '1129',
    officeName: '',
    officeCode: '3',
    state: 'FL',
    courtName: 'Northern District of Florida',
    courtDivisionName: 'Pensacola',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '294',
    groupDesignator: 'TL',
    courtId: '1129',
    officeName: '',
    officeCode: '4',
    state: 'FL',
    courtName: 'Northern District of Florida',
    courtDivisionName: 'Tallahassee',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '295',
    groupDesignator: 'TL',
    courtId: '1129',
    officeName: '',
    officeCode: '5',
    state: 'FL',
    courtName: 'Northern District of Florida',
    courtDivisionName: 'Panama City',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3A2',
    groupDesignator: 'TP',
    courtId: '113A',
    officeName: '',
    officeCode: '2',
    state: 'FL',
    courtName: 'Middle District of Florida',
    courtDivisionName: 'Ft. Myers',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3A8',
    groupDesignator: 'TP',
    courtId: '113A',
    officeName: '',
    officeCode: '8',
    state: 'FL',
    courtName: 'Middle District of Florida',
    courtDivisionName: 'Tampa',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '3A9',
    groupDesignator: 'TP',
    courtId: '113A',
    officeName: '',
    officeCode: '9',
    state: 'FL',
    courtName: 'Middle District of Florida',
    courtDivisionName: 'Ft. Myers',
    regionId: '21',
    regionName: 'ATLANTA',
  },
  {
    courtDivisionCode: '854',
    groupDesignator: 'TU',
    courtId: '1085',
    officeName: '',
    officeCode: '4',
    state: 'OK',
    courtName: 'Northern District of Oklahoma',
    courtDivisionName: 'Tulsa',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '867',
    groupDesignator: 'TU',
    courtId: '1086',
    officeName: '',
    officeCode: '7',
    state: 'OK',
    courtName: 'Eastern District of Oklahoma',
    courtDivisionName: 'Muskogee',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '401',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '1',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Beaumont',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '402',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '2',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Marshall',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '403',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '3',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Paris',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '404',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '4',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Sherman',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '405',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '5',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Texarkana',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '406',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '6',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Tyler',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '409',
    groupDesignator: 'TY',
    courtId: '0540',
    officeName: '',
    officeCode: '9',
    state: 'TX',
    courtName: 'Eastern District of Texas',
    courtDivisionName: 'Lufkin',
    regionId: '06',
    regionName: 'DALLAS',
  },
  {
    courtDivisionCode: '065',
    groupDesignator: 'UT',
    courtId: '0206',
    officeName: '',
    officeCode: '5',
    state: 'NY',
    courtName: 'Northern District of New York',
    courtDivisionName: 'Syracuse',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '066',
    groupDesignator: 'UT',
    courtId: '0206',
    officeName: '',
    officeCode: '6',
    state: 'NY',
    courtName: 'Northern District of New York',
    courtDivisionName: 'Utica',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    courtDivisionCode: '731',
    groupDesignator: 'WH',
    courtId: '0973',
    officeName: '',
    officeCode: '1',
    state: 'CA',
    courtName: 'Central District of California',
    courtDivisionName: 'San Fernando Valley',
    regionId: '16',
    regionName: 'LOS ANGELES',
  },
  {
    courtDivisionCode: '739',
    groupDesignator: 'WH',
    courtId: '0973',
    officeName: '',
    officeCode: '9',
    state: 'CA',
    courtName: 'Central District of California',
    courtDivisionName: 'Santa Barbara',
    regionId: '16',
    regionName: 'LOS ANGELES',
  },
  {
    courtDivisionCode: '832',
    groupDesignator: 'WI',
    courtId: '1083',
    officeName: '',
    officeCode: '2',
    state: 'KS',
    courtName: 'District of Kansas',
    courtDivisionName: 'Kansas City',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '835',
    groupDesignator: 'WI',
    courtId: '1083',
    officeName: '',
    officeCode: '5',
    state: 'KS',
    courtName: 'District of Kansas',
    courtDivisionName: 'Topeka',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '836',
    groupDesignator: 'WI',
    courtId: '1083',
    officeName: '',
    officeCode: '6',
    state: 'KS',
    courtName: 'District of Kansas',
    courtDivisionName: 'Wichita',
    regionId: '20',
    regionName: 'WICHITA',
  },
  {
    courtDivisionCode: '111',
    groupDesignator: 'WL',
    courtId: '0311',
    officeName: '',
    officeCode: '1',
    state: 'DE',
    courtName: 'District of Delaware',
    courtDivisionName: 'Delaware',
    regionId: '03',
    regionName: 'PHILADELPHIA',
  },
  {
    courtDivisionCode: '013',
    groupDesignator: 'WO',
    courtId: '0101',
    officeName: '',
    officeCode: '3',
    state: 'MA',
    courtName: 'District of Massachusetts',
    courtDivisionName: 'Springfield',
    regionId: '01',
    regionName: 'BOSTON',
  },
  {
    courtDivisionCode: '014',
    groupDesignator: 'WO',
    courtId: '0101',
    officeName: '',
    officeCode: '4',
    state: 'MA',
    courtName: 'District of Massachusetts',
    courtDivisionName: 'Worcester',
    regionId: '01',
    regionName: 'BOSTON',
  },
];
