const list = {
  staff1Label: 'Trial Attorney',
  staff2Label: 'Auditor',
  caseList: [
    {
      caseDiv: 400,
      staff1ProfCode: 'Adam',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Chava',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90000',
      currentCaseChapter: '11',
      hearingCode: "123",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 401,
      staff1ProfCode: 'Cayin',
      staff1ProfFirstName: "Brian               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Chavel',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90001',
      currentCaseChapter: '11',
      hearingCode: "456",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 402,
      staff1ProfCode: 'Seth',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Enosh',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90002',
      currentCaseChapter: '11',
      hearingCode: "789",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 403,
      staff1ProfCode: 'Enoch',
      staff1ProfFirstName: "Brian               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Noah',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90003',
      currentCaseChapter: '11',
      hearingCode: "012",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 404,
      staff1ProfCode: 'Shem',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Ham',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90004',
      currentCaseChapter: '12',
      hearingCode: "345",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 405,
      staff1ProfCode: 'Micah',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'David',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90005',
      currentCaseChapter: '05',
      hearingCode: "678",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 406,
      staff1ProfCode: 'Isaiah',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Marry',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90006',
      currentCaseChapter: '7A',
      hearingCode: "901",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 407,
      staff1ProfCode: 'Aaron',
      staff1ProfFirstName: "Brian               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Yosi',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90007',
      currentCaseChapter: '7B',
      hearingCode: "234",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 408,
      staff1ProfCode: 'Sarah',
      staff1ProfFirstName: "Joe               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Matt',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90008',
      currentCaseChapter: '12',
      hearingCode: "567",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 409,
      staff1ProfCode: 'Marta',
      staff1ProfFirstName: "Joe               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'Elizabeth',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90009',
      currentCaseChapter: '11',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
  ]
};

export { list };
