# Example using map for more complex pattern matching
# TODO: We need to replace all nginx variables with environment variables so that they are not corrupted by deployment scripts
# ${NGINX_REQUEST_URI_VAR_VALUE} $request_uri
# ${NGINX_BLOCK_SCAN_VAR_VALUE} $block_scan
map ${NGINX_REQUEST_URI_VAR_VALUE} ${NGINX_BLOCK_SCAN_VAR_VALUE} {
    "~*^/wp-admin" 1;
    default 0;
}

server {
    listen 8080;
    listen [::]:8080;

    root /home/site/wwwroot;

    # The server_name, though required, will be ignored in the context of webapp Proxy service.
    server_name  example.com www.example.com;
    port_in_redirect off;

    error_page   404  /404.html;
    error_page   403  /403.html;
    error_page   500 502 503 504  /50x.html;

    ## Set Content-Security-Policy
    ## NOTE on variables:
    ##   OKTA_URL                          - Url for the okta host
    ##   CSP_API_SERVER_HOST               - refers to the backend api host uri
    ##   CSP_USTP_ISSUE_COLLECTOR_HASH     - USTP issue collector hash
    ##   CSP_CAMS_REACT_SELECT_HASH        - React-Select hash
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header X-XSS-Protection "1; mode=block" always; # legacy, still used
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' code.jquery.com atl.cld.prd.ust.doj.gov; connect-src 'self' ${CSP_API_SERVER_HOST} ${OKTA_URL} clientsdk.launchdarkly.us clientstream.launchdarkly.us events.launchdarkly.us js.monitor.azure.com usgovvirginia-1.in.applicationinsights.azure.us; img-src 'self' data: ; style-src 'self' '${CSP_CAMS_REACT_SELECT_HASH}' '${CSP_USTP_ISSUE_COLLECTOR_HASH}'; base-uri 'self'; form-action 'self'; frame-src 'self' ${OKTA_URL} atl.cld.prd.ust.doj.gov" always;

    if (${NGINX_BLOCK_SCAN_VAR_VALUE}) {
        return 404;
    }

    ## Disable access to all dot (.) files and directories
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }

    location = /robots.txt {
        try_files $uri =404;
    }

    # Allowlisted static file types
    location ~* \.(html|js|json|png|jpg|svg|webp|css|ttf|woff|woff2)$ {
        access_log off;
        expires 1h;
    }

    # Block all other "file-like" requests (e.g. .php, .exe, .bak)
    location ~* \.[a-z0-9][a-z0-9]+$ {
        return 404;
    }

    location / {
        index index.html;
        try_files ${NGINX_URI_VAR_VALUE} ${NGINX_URI_VAR_VALUE}/ /index.html =404;
    }
}
