/**
 * Parity Validation: ATS Cleansing Pipeline
 *
 * This test validates that the TypeScript cleansing pipeline produces identical
 * output to the Python prototype by comparing against the reference TSV data.
 *
 * This test validates field-by-field parity (classification, courtIds, mapType)
 * for all 8,244 appointments.
 *
 * The reference TSV files are maintained in test-data/ and were originally
 * generated by the Python prototype in .ustp-cams-fdp/.
 */
import { describe, test, expect } from 'vitest';
import { CleansingClassification } from './ats-cleansing-types';
import { loadOverrides, loadTsvRows, cleanseRow } from './ats-tsv-test-utils';

describe('TSV Parity Validation', () => {
  test('should match prototype output for all TSV rows', () => {
    // Load override data and TSV rows
    const overridesCache = loadOverrides();
    const { rows } = loadTsvRows();

    console.log(`\nLoaded ${overridesCache.size} trustee overrides`);
    console.log(`\nValidating ${rows.length} appointments from TSV...\n`);

    const mismatches: Array<{
      row: number;
      trusteeid: string;
      field: string;
      expected: string | string[];
      actual: string | string[];
      notes?: string;
    }> = [];

    let cleanCount = 0;
    let autoRecoverableCount = 0;
    let problematicCount = 0;
    let uncleansableCount = 0;
    let skipCount = 0;

    rows.forEach((row, idx) => {
      const rowNum = idx + 2; // +2 because: +1 for 0-index, +1 for header row

      // Run through cleansing pipeline
      const result = cleanseRow(row, overridesCache);

      // Expected values from TSV (handle both comma and semicolon delimiters)
      const expectedClassification = row.classification;
      const expectedCourtIds = row.court_ids
        ? row.court_ids.split(/[,;]/).map((id) => id.trim())
        : [];
      const expectedMapType = row.map_type;

      // Actual values from TypeScript
      const actualClassification = result.classification;
      const actualCourtIds = result.courtIds || [];
      const actualMapType = result.mapType;

      // Track counts
      switch (actualClassification) {
        case CleansingClassification.CLEAN:
          cleanCount++;
          break;
        case CleansingClassification.AUTO_RECOVERABLE:
          autoRecoverableCount++;
          break;
        case CleansingClassification.PROBLEMATIC:
          problematicCount++;
          break;
        case CleansingClassification.UNCLEANSABLE:
          uncleansableCount++;
          break;
        case CleansingClassification.SKIP:
          skipCount++;
          break;
      }

      // Compare classification
      if (actualClassification !== expectedClassification) {
        mismatches.push({
          row: rowNum,
          trusteeid: row.trusteeid,
          field: 'classification',
          expected: expectedClassification,
          actual: actualClassification,
          notes: `DISTRICT="${row.district}", STATE="${row.serving_state}"`,
        });
      }

      // Compare court IDs (only for successful cleansing)
      if (expectedClassification === 'CLEAN' || expectedClassification === 'AUTO_RECOVERABLE') {
        const expectedSorted = [...expectedCourtIds].sort();
        const actualSorted = [...actualCourtIds].sort();

        // Only report mismatch if arrays actually differ
        if (
          expectedSorted.length !== actualSorted.length ||
          !expectedSorted.every((val, idx) => val === actualSorted[idx])
        ) {
          mismatches.push({
            row: rowNum,
            trusteeid: row.trusteeid,
            field: 'courtIds',
            expected: expectedSorted.join(';'),
            actual: actualSorted.join(';'),
          });
        }
      }

      // Compare map type
      if (actualMapType !== expectedMapType) {
        mismatches.push({
          row: rowNum,
          trusteeid: row.trusteeid,
          field: 'mapType',
          expected: expectedMapType,
          actual: actualMapType,
        });
      }
    });

    // Print summary
    console.log('\n=== VALIDATION SUMMARY ===');
    console.log(`Total appointments: ${rows.length}`);
    console.log(`CLEAN: ${cleanCount} (expected ~5496)`);
    console.log(`AUTO_RECOVERABLE: ${autoRecoverableCount} (expected ~2635)`);
    console.log(`PROBLEMATIC: ${problematicCount} (expected ~80)`);
    console.log(`UNCLEANSABLE: ${uncleansableCount} (expected ~33)`);
    console.log(`SKIP: ${skipCount}`);
    console.log(`\nMismatches: ${mismatches.length}`);

    // Group mismatches by type
    const classificationMismatches = mismatches.filter((m) => m.field === 'classification');
    const courtIdMismatches = mismatches.filter((m) => m.field === 'courtIds');
    const mapTypeMismatches = mismatches.filter((m) => m.field === 'mapType');
    console.log(`  Classification: ${classificationMismatches.length}`);
    console.log(`  CourtIds: ${courtIdMismatches.length}`);
    console.log(`  MapType: ${mapTypeMismatches.length}`);

    if (mismatches.length > 0) {
      console.log('\n=== MISMATCHES ===');
      mismatches.slice(0, 20).forEach((m) => {
        console.log(
          `Row ${m.row} (TRU_ID=${m.trusteeid}): ${m.field} - expected "${m.expected}", got "${m.actual}"${m.notes ? ` - ${m.notes}` : ''}`,
        );
      });
      if (mismatches.length > 20) {
        console.log(`... and ${mismatches.length - 20} more mismatches`);
      }
    }

    // Assertion
    expect(mismatches.length).toBe(0);
  });
});
