const list = [
  { CASE_DIV: 400, STAFF1_PROF_CODE: 'Adam', STAFF2_PROF_CODE: 'Chava', CASE_YEAR: '22', CASE_NUMBER: '90000', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 401, STAFF1_PROF_CODE: 'Cayin', STAFF2_PROF_CODE: 'Chavel', CASE_YEAR: '22', CASE_NUMBER: '90001', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 402, STAFF1_PROF_CODE: 'Seth', STAFF2_PROF_CODE: 'Enosh', CASE_YEAR: '22', CASE_NUMBER: '90002', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 403, STAFF1_PROF_CODE: 'Enoch', STAFF2_PROF_CODE: 'Noah', CASE_YEAR: '22', CASE_NUMBER: '90003', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 404, STAFF1_PROF_CODE: 'Shem', STAFF2_PROF_CODE: 'Ham', CASE_YEAR: '23', CASE_NUMBER: '90004', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 405, STAFF1_PROF_CODE: 'Micah', STAFF2_PROF_CODE: 'David', CASE_YEAR: '23', CASE_NUMBER: '90005', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 406, STAFF1_PROF_CODE: 'Isaiah', STAFF2_PROF_CODE: 'Marry', CASE_YEAR: '23', CASE_NUMBER: '90006', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 407, STAFF1_PROF_CODE: 'Aaron', STAFF2_PROF_CODE: 'Yosi', CASE_YEAR: '23', CASE_NUMBER: '90007', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 408, STAFF1_PROF_CODE: 'Sarah', STAFF2_PROF_CODE: 'Matt', CASE_YEAR: '24', CASE_NUMBER: '90008', CURR_CASE_CHAPT: '11' },
  { CASE_DIV: 409, STAFF1_PROF_CODE: 'Marta', STAFF2_PROF_CODE: 'Elizabeth', CASE_YEAR: '24', CASE_NUMBER: '90009', CURR_CASE_CHAPT: '11' },
];

export { list };
