const ACMS_CAMS_TRANSITION_DAILY_SYNC = 'ACMS-CAMS-TRANSITION-DAILY-SYNC';
const BACKFILL_CASE_APPOINTMENT_DATES = 'BACKFILL-CASE-APPOINTMENT-DATES';
const BACKFILL_CONSOLIDATION_ORDER_TASK_DATE = 'BACKFILL-CONSOLIDATION-ORDER-TASK-DATE';
const BACKFILL_PHONETIC_TOKENS = 'BACKFILL-PHONETIC-TOKENS';
const BACKFILL_TRANSFER_ORDER_TASK_DATE = 'BACKFILL-TRANSFER-ORDER-TASK-DATE';
const BACKFILL_TRUSTEE_APPOINTMENTS_DOWNSTREAM = 'BACKFILL-TRUSTEE-APPOINTMENTS-DOWNSTREAM';
const BACKFILL_TRUSTEE_PHONETIC_TOKENS = 'BACKFILL-TRUSTEE-PHONETIC-TOKENS';
const BACKFILL_TRUSTEE_PROFESSIONAL_IDS = 'BACKFILL-TRUSTEE-PROFESSIONAL-IDS';
const BACKFILL_TRUSTEE_VERIFICATION_TASK_DATE = 'BACKFILL-TRUSTEE-VERIFICATION-TASK-DATE';
const CASE_ASSIGNMENT_EVENT = 'CASE-ASSIGNMENT-EVENT';
const CASE_CLOSED_EVENT = 'CASE-CLOSED-EVENT';
const FIX_CHAPTER_7_APPOINTMENTS = 'FIX-CHAPTER-7-APPOINTMENTS';
const IMPORT_ZOOM_CSV = 'IMPORT-ZOOM-CSV';
const MIGRATE_CASE_APPOINTMENTS = 'MIGRATE-CASE-APPOINTMENTS';
const MIGRATE_TRUSTEES = 'MIGRATE-TRUSTEES';
const RESYNC_CASES_BY_DATE = 'RESYNC-CASES-BY-DATE';
const STAFF_ASSIGNMENT_DOWNSTREAM = 'STAFF-ASSIGNMENT-DOWNSTREAM';
const SYNC_CASES_PAGE = 'SYNC-CASES-PAGE';
const SYNC_DELETED_CASES = 'SYNC-DELETED-CASES';
const SYNC_TRUSTEE_CASE_APPOINTMENTS = 'SYNC-TRUSTEE-CASE-APPOINTMENTS';
const SYNC_TRUSTEE_DUE_DATE_METRICS = 'SYNC-TRUSTEE-DUE-DATE-METRICS';
const SYNC_TRUSTEE_NOTES_METRICS = 'SYNC-TRUSTEE-NOTES-METRICS';
const TRUSTEE_APPOINTMENT_DOWNSTREAM = 'TRUSTEE-APPOINTMENT-DOWNSTREAM';
const TRUSTEE_MATCH_VERIFICATION_REMAP = 'TRUSTEE-MATCH-VERIFICATION-REMAP';
const TRUSTEE_APPOINTMENT_EVENT = 'TRUSTEE-APPOINTMENT-EVENT';

const ModuleNames = {
  ACMS_CAMS_TRANSITION_DAILY_SYNC,
  BACKFILL_CASE_APPOINTMENT_DATES,
  BACKFILL_CONSOLIDATION_ORDER_TASK_DATE,
  BACKFILL_PHONETIC_TOKENS,
  BACKFILL_TRANSFER_ORDER_TASK_DATE,
  BACKFILL_TRUSTEE_APPOINTMENTS_DOWNSTREAM,
  BACKFILL_TRUSTEE_PHONETIC_TOKENS,
  BACKFILL_TRUSTEE_PROFESSIONAL_IDS,
  BACKFILL_TRUSTEE_VERIFICATION_TASK_DATE,
  CASE_ASSIGNMENT_EVENT,
  CASE_CLOSED_EVENT,
  FIX_CHAPTER_7_APPOINTMENTS,
  IMPORT_ZOOM_CSV,
  MIGRATE_CASE_APPOINTMENTS,
  MIGRATE_TRUSTEES,
  RESYNC_CASES_BY_DATE,
  STAFF_ASSIGNMENT_DOWNSTREAM,
  SYNC_CASES_PAGE,
  SYNC_DELETED_CASES,
  SYNC_TRUSTEE_CASE_APPOINTMENTS,
  SYNC_TRUSTEE_DUE_DATE_METRICS,
  SYNC_TRUSTEE_NOTES_METRICS,
  TRUSTEE_APPOINTMENT_DOWNSTREAM,
  TRUSTEE_MATCH_VERIFICATION_REMAP,
  TRUSTEE_APPOINTMENT_EVENT,
} as const;

export default ModuleNames;
