const BACKFILL_PHONETIC_TOKENS = 'BACKFILL-PHONETIC-TOKENS';
const CASE_ASSIGNMENT_EVENT = 'CASE-ASSIGNMENT-EVENT';
const CASE_CLOSED_EVENT = 'CASE-CLOSED-EVENT';

const ModuleNames = {
  BACKFILL_PHONETIC_TOKENS,
  CASE_ASSIGNMENT_EVENT,
  CASE_CLOSED_EVENT,
} as const;

export default ModuleNames;
