const BACKFILL_PHONETIC_TOKENS = 'BACKFILL-PHONETIC-TOKENS';
const BACKFILL_CASE_APPOINTMENT_DATES = 'BACKFILL-CASE-APPOINTMENT-DATES';
const BACKFILL_TRUSTEE_PHONETIC_TOKENS = 'BACKFILL-TRUSTEE-PHONETIC-TOKENS';
const CASE_ASSIGNMENT_EVENT = 'CASE-ASSIGNMENT-EVENT';
const CASE_CLOSED_EVENT = 'CASE-CLOSED-EVENT';
const IMPORT_ZOOM_CSV = 'IMPORT-ZOOM-CSV';
const MIGRATE_CASE_APPOINTMENTS = 'MIGRATE-CASE-APPOINTMENTS';
const MIGRATE_TRUSTEES = 'MIGRATE-TRUSTEES';
const SYNC_CASES_PAGE = 'SYNC-CASES-PAGE';
const SYNC_DELETED_CASES = 'SYNC-DELETED-CASES';
const SYNC_TRUSTEE_APPOINTMENTS = 'SYNC-TRUSTEE-APPOINTMENTS';
const SYNC_TRUSTEE_DUE_DATE_METRICS = 'SYNC-TRUSTEE-DUE-DATE-METRICS';
const TRUSTEE_APPOINTMENT_EVENT = 'TRUSTEE-APPOINTMENT-EVENT';
const SYNC_TRUSTEE_NOTES_METRICS = 'SYNC-TRUSTEE-NOTES-METRICS';
const RESYNC_CASES_BY_DATE = 'RESYNC-CASES-BY-DATE';

const ModuleNames = {
  BACKFILL_PHONETIC_TOKENS,
  BACKFILL_CASE_APPOINTMENT_DATES,
  BACKFILL_TRUSTEE_PHONETIC_TOKENS,
  CASE_ASSIGNMENT_EVENT,
  CASE_CLOSED_EVENT,
  IMPORT_ZOOM_CSV,
  MIGRATE_CASE_APPOINTMENTS,
  MIGRATE_TRUSTEES,
  SYNC_CASES_PAGE,
  SYNC_DELETED_CASES,
  SYNC_TRUSTEE_APPOINTMENTS,
  SYNC_TRUSTEE_DUE_DATE_METRICS,
  TRUSTEE_APPOINTMENT_EVENT,
  SYNC_TRUSTEE_NOTES_METRICS,
  RESYNC_CASES_BY_DATE,
} as const;

export default ModuleNames;
