#!/usr/bin/env tsx

/**
 * Fixture Synthesis Script
 *
 * Builds mongo-fixture.json and sqlserver-fixture.json containing only the
 * data required by the Playwright E2E specs. Reads from the harvested fixtures
 * (mongo-harvested.json / sqlserver-harvested.json) produced by the harvest
 * scripts, selects/synthesizes the minimum required records, and nulls all PII
 * fields. Faker replacements are generated at seed time by seed-database.ts and
 * seed-sqlserver.ts.
 *
 * Input:  fixtures/mongo-harvested.json    (gitignored, produced by harvest-mongo.ts)
 *         fixtures/sqlserver-harvested.json (gitignored, produced by harvest-sqlserver.ts)
 * Output: fixtures/mongo-fixture.json      (committed)
 *         fixtures/sqlserver-fixture.json  (committed)
 *
 * Required cases:
 *   091-69-12345  — KNOWN_GOOD_TRANSFER_TO_CASE_ID  (case-notes.spec.ts, transfer-orders.spec.ts)
 *   081-65-67641  — KNOWN_GOOD_TRANSFER_FROM_CASE_ID (transfer-orders.spec.ts)
 *   081-18-61881  — pending transfer order test case AND consolidation add-case target
 *
 * PII fields nulled here (regenerated by Faker at seed time):
 *   cases/orders/consolidations:
 *     debtor.name, debtor.ssn, debtor.taxId, debtor.address*, debtor.cityStateZipCountry,
 *     debtor.additionalIdentifiers, jointDebtor.* (same), judgeName, caseTitle,
 *     debtorAttorney.name, debtorAttorney.phone, debtorAttorney.email,
 *     debtorAttorney.address*, debtorAttorney.cityStateZipCountry
 *
 * Usage: tsx ./scripts/synthesize-fixtures.ts
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve } from 'path';
import { randomUUID } from 'crypto';

const FIXTURES_DIR = resolve(__dirname, '../fixtures');

const KNOWN_CASE_IDS = ['091-69-12345', '081-65-67641', '081-18-61881'];

type MongoDocument = Record<string, unknown>;

// ── Load full harvested fixtures ──────────────────────────────────────────────

const fullMongo = JSON.parse(
  readFileSync(resolve(FIXTURES_DIR, 'mongo-harvested.json'), 'utf-8'),
) as { harvestedAt: string; collections: Record<string, MongoDocument[]> };

const fullSql = JSON.parse(
  readFileSync(resolve(FIXTURES_DIR, 'sqlserver-harvested.json'), 'utf-8'),
) as {
  harvestedAt: string;
  sourceCaseIds: string[];
  tables: Record<string, { columns: unknown[]; rows: Record<string, unknown>[] }>;
};

// ── PII stripping ─────────────────────────────────────────────────────────────

function nullDebtor(debtor: unknown): Record<string, null> | null {
  if (!debtor) return null;
  return {
    name: null,
    address1: null,
    address2: null,
    address3: null,
    cityStateZipCountry: null,
    taxId: null,
    ssn: null,
    additionalIdentifiers: null,
  };
}

function nullAttorney(attorney: unknown): Record<string, null | string> | null {
  if (!attorney) return null;
  return {
    name: null,
    address1: null,
    address2: null,
    address3: null,
    cityStateZipCountry: null,
    phone: null,
    email: null,
    office: null,
  };
}

function stripCasePii(doc: MongoDocument): MongoDocument {
  const out = { ...doc };
  out.caseTitle = null;
  out.judgeName = null;
  if (out.debtor) out.debtor = nullDebtor(out.debtor);
  if (out.jointDebtor) out.jointDebtor = nullDebtor(out.jointDebtor);
  if (out.debtorAttorney) out.debtorAttorney = nullAttorney(out.debtorAttorney);
  return out;
}

function stripOrderPii(doc: MongoDocument): MongoDocument {
  const out = { ...doc };
  out.caseTitle = null;
  if (out.debtor) out.debtor = nullDebtor(out.debtor);
  if (out.jointDebtor) out.jointDebtor = nullDebtor(out.jointDebtor);
  if (out.debtorAttorney) out.debtorAttorney = nullAttorney(out.debtorAttorney);
  if (out.newCase && typeof out.newCase === 'object') {
    const nc = { ...(out.newCase as MongoDocument) };
    nc.caseTitle = null;
    if (nc.debtor) nc.debtor = nullDebtor(nc.debtor);
    if (nc.jointDebtor) nc.jointDebtor = nullDebtor(nc.jointDebtor);
    if (nc.debtorAttorney) nc.debtorAttorney = nullAttorney(nc.debtorAttorney);
    out.newCase = nc;
  }
  return out;
}

function stripConsolidationPii(doc: MongoDocument): MongoDocument {
  const out = { ...doc };
  out.caseTitle = null;
  if (out.debtor) out.debtor = nullDebtor(out.debtor);
  if (out.leadCase && typeof out.leadCase === 'object') {
    const lc = { ...(out.leadCase as MongoDocument) };
    lc.caseTitle = null;
    if (lc.debtor) lc.debtor = nullDebtor(lc.debtor);
    if (lc.debtorAttorney) lc.debtorAttorney = nullAttorney(lc.debtorAttorney);
    out.leadCase = lc;
  }
  // Rename childCases → memberCases (post-migration field name required by the API type)
  const childCases = (out.childCases ?? out.memberCases) as MongoDocument[] | undefined;
  delete out.childCases;
  if (Array.isArray(childCases)) {
    out.memberCases = childCases.map((cc) => {
      const c = { ...cc };
      c.caseTitle = null;
      if (c.debtor) c.debtor = nullDebtor(c.debtor);
      if (c.debtorAttorney) c.debtorAttorney = nullAttorney(c.debtorAttorney);
      return c;
    });
  }
  return out;
}

// ── Case synthesis ────────────────────────────────────────────────────────────

const fullSqlAoCs = fullSql.tables.AO_CS.rows;
const fullSqlAoCsDiv = fullSql.tables.AO_CS_DIV.rows;

function buildSyncedCase(caseId: string): MongoDocument {
  const [divCode, year, num] = caseId.split('-');
  const divRow = fullSqlAoCsDiv.find((r) => r.CS_DIV_ACMS === divCode);
  const csRow = fullSqlAoCs.find(
    (r) => r.CS_DIV === divRow?.CS_DIV && r.CASE_ID === `${year}-${num}`,
  );
  if (!csRow) throw new Error(`Cannot build SYNCED_CASE for ${caseId}: no AO_CS row found`);

  const isBuffalo = divCode === '091';

  return {
    _id: randomUUID().replace(/-/g, '').substring(0, 24),
    id: randomUUID(),
    courtDivisionCode: divCode,
    caseId,
    caseNumber: `${year}-${num}`,
    caseTitle: null, // ← Faker at seed time
    dateFiled: csRow.CS_DATE_FILED
      ? new Date(csRow.CS_DATE_FILED as string).toISOString().split('T')[0]
      : '2020-01-01',
    dxtrId: String(csRow.CS_CASEID),
    chapter: String(csRow.CS_CHAPTER ?? '15'),
    courtId: isBuffalo ? '0209' : '0208',
    courtName: isBuffalo ? 'Western District of New York' : 'Southern District of New York',
    courtDivisionName: isBuffalo ? 'Buffalo' : 'Manhattan',
    judgeName: null, // ← Faker at seed time
    regionId: '02',
    regionName: 'NEW YORK',
    petitionCode: csRow.CS_VOL_INVOL === 'v' ? 'VP' : 'IP',
    debtorTypeCode: 'IB',
    debtor: {
      name: null, // ← Faker at seed time
      address1: null,
      address2: null,
      address3: null,
      cityStateZipCountry: null,
      taxId: null,
      ssn: null,
      additionalIdentifiers: null,
    },
    debtorTypeLabel: 'Individual Business',
    petitionLabel: 'Voluntary',
    debtorAttorney: null,
    documentType: 'SYNCED_CASE',
    updatedOn: new Date().toISOString(),
    updatedBy: { id: 'SYSTEM', name: 'SYSTEM' },
  };
}

const syncedCases: MongoDocument[] = KNOWN_CASE_IDS.map((id) => {
  const existing = fullMongo.collections.cases.find(
    (c) => c.caseId === id && c.documentType === 'SYNCED_CASE',
  );
  const doc =
    existing ??
    (() => {
      console.log(`  Synthesizing SYNCED_CASE for ${id} (not in harvest)`);
      return buildSyncedCase(id);
    })();
  return stripCasePii(doc);
});

// ── Orders ────────────────────────────────────────────────────────────────────

// Keep the known-good transfer (081-65-67641 → 091-69-12345).
// The transfer spec uses '18-61881' as a manually-entered suggested case number, not as an order FROM case.
// Deduplicate — the harvest may include multiple pending orders for the same caseId.
// Ensure every order has a newCase — synthesize one from SQL if missing.
const seenOrderCaseIds = new Set<string>();
const transferOrders = fullMongo.collections.orders
  .filter((o) => {
    if (o.orderType !== 'transfer' || o.status !== 'pending') return false;
    if (o.caseId !== '081-65-67641') return false;
    if (seenOrderCaseIds.has(o.caseId as string)) return false;
    seenOrderCaseIds.add(o.caseId as string);
    return true;
  })
  .map((o) => {
    const stripped = stripOrderPii(o);
    // Synthesize newCase if missing — required by UI to render transfer accordion controls
    if (!stripped.newCase) {
      const suggestedNum = stripped.docketSuggestedCaseNumber as string | undefined;
      // Use 091-69-12345 as the newCase target (it's in our case set and is the known transfer-to)
      stripped.newCase = buildSyncedCase('091-69-12345');
      if (suggestedNum) {
        (stripped.newCase as MongoDocument).caseNumber = suggestedNum;
      }
      // Strip PII from the synthesized newCase
      const nc = stripped.newCase as MongoDocument;
      nc.caseTitle = null;
      if (nc.debtor) nc.debtor = nullDebtor(nc.debtor);
    }
    return stripped;
  });

// ── Consolidations ────────────────────────────────────────────────────────────

// Keep one pending consolidation where 081-18-61881 is NOT a member (so the spec can add it).
// If no matching consolidation exists in the harvest, synthesize one directly.
const consolidationWithKnownCase = fullMongo.collections.consolidations.find(
  (c) =>
    c.status === 'pending' &&
    (Array.isArray(c.childCases) || Array.isArray(c.memberCases)) &&
    !((c.childCases ?? c.memberCases) as MongoDocument[]).some(
      (cc) => cc.caseId === '081-18-61881',
    ),
);

function buildSyntheticConsolidation(): MongoDocument {
  const memberCase1 = buildSyncedCase('081-65-67641');

  // ConsolidationOrderCase extends CaseSummary — add required order-case fields
  function toOrderCase(c: MongoDocument): MongoDocument {
    return {
      ...c,
      docketEntries: [],
      orderDate: new Date().toISOString().split('T')[0],
    };
  }

  // memberCases contains 65-67641 only.
  // 18-61881 is intentionally excluded so the consolidation spec can add it via the modal.
  return {
    _id: randomUUID().replace(/-/g, '').substring(0, 24),
    id: randomUUID(),
    consolidationId: randomUUID(),
    documentType: 'CONSOLIDATION_ORDER',
    orderType: 'consolidation',
    status: 'pending',
    orderDate: new Date().toISOString().split('T')[0],
    courtName: 'Southern District of New York',
    courtDivisionCode: '081',
    jobId: 1001,
    memberCases: [toOrderCase(memberCase1)],
    updatedOn: new Date().toISOString(),
    updatedBy: { id: 'SYSTEM', name: 'SYSTEM' },
  };
}

const consolidations = consolidationWithKnownCase
  ? [stripConsolidationPii(consolidationWithKnownCase)]
  : (() => {
      console.log(
        '  Synthesizing consolidation order (081-18-61881 not in any harvest consolidation)',
      );
      return [stripConsolidationPii(buildSyntheticConsolidation())];
    })();

// ── Synthesize SYNCED_CASE docs for all cases referenced in orders/consolidations ──
//
// The transfer and consolidation accordions look up cases from MongoDB by caseId.
// Any caseId appearing in a memberCase or newCase that isn't already in syncedCases
// needs a SYNCED_CASE document so the backend can resolve it.

const allReferencedCaseIds = new Set<string>(KNOWN_CASE_IDS);

// From transfer orders — newCase caseId
transferOrders.forEach((o) => {
  const nc = o.newCase as MongoDocument | undefined;
  if (nc?.caseId) allReferencedCaseIds.add(nc.caseId as string);
});

// From consolidations — memberCases caseIds
consolidations.forEach((c) => {
  (((c.memberCases ?? c.childCases) as MongoDocument[]) ?? []).forEach((cc) => {
    if (cc.caseId) allReferencedCaseIds.add(cc.caseId as string);
  });
});

// Add SYNCED_CASE for any referenced case not already covered
const existingSyncedIds = new Set(syncedCases.map((c) => c.caseId as string));
for (const id of allReferencedCaseIds) {
  if (existingSyncedIds.has(id)) continue;
  // Only synthesize if we have SQL data for it; skip cases outside our SQL fixture
  const [divCode, year, num] = id.split('-');
  const divRow = fullSqlAoCsDiv.find((r) => r.CS_DIV_ACMS === divCode);
  const csRow =
    divRow && fullSqlAoCs.find((r) => r.CS_DIV === divRow.CS_DIV && r.CASE_ID === `${year}-${num}`);
  if (csRow) {
    console.log(`  Synthesizing SYNCED_CASE for referenced case ${id}`);
    syncedCases.push(stripCasePii(buildSyncedCase(id)));
    existingSyncedIds.add(id);
  }
}

// ── Trustees ──────────────────────────────────────────────────────────────────

// Synthesized — no real data needed, trustees.spec.ts just checks the table renders.
// trusteeId must be a UUID — the backend queries by trusteeId and the nav link uses it.
const TRUSTEE_UUID = 'aaaabbbb-cccc-dddd-eeee-ffff00000001';
const trustees: MongoDocument[] = [
  {
    _id: '000000000000000000000001',
    id: 'test-trustee-0',
    trusteeId: TRUSTEE_UUID,
    documentType: 'TRUSTEE',
    name: null, // ← Faker at seed time
    professional: {
      firstName: null, // ← Faker at seed time
      lastName: null, // ← Faker at seed time
      office: null, // ← Faker at seed time
      phone: null,
      email: null,
    },
    updatedOn: new Date().toISOString(),
    updatedBy: { id: 'SYSTEM', name: 'SYSTEM' },
  },
];

// ── User groups ───────────────────────────────────────────────────────────────

// Fixed IDs required by the app; names are not PII-sensitive (role-based mocks).
const userGroups: MongoDocument[] = [
  {
    _id: '000000000000000000000010',
    id: 'group-attorneys',
    groupName: 'USTP CAMS Trial Attorney',
    users: [
      { id: 'attorney-1', name: 'Weis, Brandon' },
      { id: 'attorney-2', name: 'Smith, Jane' },
      { id: 'attorney-3', name: 'Johnson, Bob' },
    ],
  },
  {
    _id: '000000000000000000000011',
    id: 'group-auditors',
    groupName: 'USTP CAMS Auditor',
    users: [
      { id: 'auditor-1', name: 'Williams, Sarah' },
      { id: 'auditor-2', name: 'Brown, Michael' },
      { id: 'auditor-3', name: 'Davis, Emily' },
    ],
  },
];

// ── Mongo fixture ─────────────────────────────────────────────────────────────

const mongoFixture = {
  synthesizedAt: new Date().toISOString(),
  collections: {
    cases: syncedCases,
    consolidations,
    orders: transferOrders,
    trustees,
    'user-groups': userGroups,
  },
};

// ── SQL Server synthesis ──────────────────────────────────────────────────────

const aoCsDiv = fullSql.tables.AO_CS_DIV;
const aoCs = fullSql.tables.AO_CS;

const knownCaseKeys: Array<{ csCaseId: number; courtId: string }> = [];
for (const caseId of KNOWN_CASE_IDS) {
  const [divCode, year, num] = caseId.split('-');
  const divRow = aoCsDiv.rows.find((r) => r.CS_DIV_ACMS === divCode);
  if (!divRow) {
    console.warn(`CS_DIV_ACMS not found for ${caseId}`);
    continue;
  }
  const csRow = aoCs.rows.find((r) => r.CS_DIV === divRow.CS_DIV && r.CASE_ID === `${year}-${num}`);
  if (!csRow) {
    console.warn(`AO_CS row not found for ${caseId}`);
    continue;
  }
  knownCaseKeys.push({ csCaseId: csRow.CS_CASEID as number, courtId: csRow.COURT_ID as string });
}

if (knownCaseKeys.length !== KNOWN_CASE_IDS.length) {
  console.error(`Only resolved ${knownCaseKeys.length}/${KNOWN_CASE_IDS.length} SQL case keys`);
  process.exit(1);
}

const caseKeySet = new Set(knownCaseKeys.map((k) => `${k.csCaseId}|${k.courtId}`));

function filterCaseTable(rows: Record<string, unknown>[]): Record<string, unknown>[] {
  const seen = new Set<string>();
  return rows.filter((r) => {
    const key = `${r.CS_CASEID}|${r.COURT_ID}`;
    if (!caseKeySet.has(key) || seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

const sqlFixture = {
  synthesizedAt: new Date().toISOString(),
  sourceCaseIds: KNOWN_CASE_IDS,
  tables: {
    AO_COURT: fullSql.tables.AO_COURT,
    AO_REGION: fullSql.tables.AO_REGION,
    AO_GRP_DES: fullSql.tables.AO_GRP_DES,
    AO_CS_DIV: fullSql.tables.AO_CS_DIV,
    AO_OFFICE: fullSql.tables.AO_OFFICE,
    AO_PDF_PATH: fullSql.tables.AO_PDF_PATH,
    AO_CS: {
      columns: fullSql.tables.AO_CS.columns,
      rows: filterCaseTable(fullSql.tables.AO_CS.rows),
    },
    AO_TX: {
      columns: fullSql.tables.AO_TX.columns,
      rows: filterCaseTable(fullSql.tables.AO_TX.rows),
    },
    AO_PY: {
      columns: fullSql.tables.AO_PY.columns,
      rows: filterCaseTable(fullSql.tables.AO_PY.rows),
    },
    AO_ALIAS: {
      columns: fullSql.tables.AO_ALIAS.columns,
      rows: filterCaseTable(fullSql.tables.AO_ALIAS.rows),
    },
    AO_SSN: {
      columns: fullSql.tables.AO_SSN.columns,
      rows: filterCaseTable(fullSql.tables.AO_SSN.rows),
    },
    AO_TAXID: {
      columns: fullSql.tables.AO_TAXID.columns,
      rows: filterCaseTable(fullSql.tables.AO_TAXID.rows),
    },
    AO_AT: {
      columns: fullSql.tables.AO_AT.columns,
      rows: filterCaseTable(fullSql.tables.AO_AT.rows),
    },
    AO_DC: {
      columns: fullSql.tables.AO_DC.columns,
      rows: filterCaseTable(fullSql.tables.AO_DC.rows),
    },
    AO_DE: {
      columns: fullSql.tables.AO_DE.columns,
      rows: filterCaseTable(fullSql.tables.AO_DE.rows),
    },
  },
};

// ── Write ─────────────────────────────────────────────────────────────────────

mkdirSync(FIXTURES_DIR, { recursive: true });
writeFileSync(resolve(FIXTURES_DIR, 'mongo-fixture.json'), JSON.stringify(mongoFixture, null, 2));
writeFileSync(resolve(FIXTURES_DIR, 'sqlserver-fixture.json'), JSON.stringify(sqlFixture, null, 2));

console.log('✓ mongo-fixture.json');
Object.entries(mongoFixture.collections).forEach(([name, docs]) =>
  console.log(`  ${name}: ${docs.length} documents`),
);
console.log('✓ sqlserver-fixture.json');
Object.entries(sqlFixture.tables).forEach(([name, t]) =>
  console.log(`  ${name}: ${(t as { rows: unknown[] }).rows.length} rows`),
);
