const list = {
  staff1Label: 'Trial Attorney',
  staff2Label: 'Auditor',
  caseList: [
    {
      caseDiv: 400,
      staff1ProfCode: 'A1',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90000',
      currentCaseChapter: '11',
      hearingCode: "123",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 401,
      staff1ProfCode: 'A2',
      staff1ProfFirstName: "Brian               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90001',
      currentCaseChapter: '11',
      hearingCode: "456",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 402,
      staff1ProfCode: 'A1',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90002',
      currentCaseChapter: '11',
      hearingCode: "789",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 403,
      staff1ProfCode: 'A2',
      staff1ProfFirstName: "Brian               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B1',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '22',
      caseNumber: '90003',
      currentCaseChapter: '11',
      hearingCode: "012",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 404,
      staff1ProfCode: 'A1',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90004',
      currentCaseChapter: '12',
      hearingCode: "345",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 405,
      staff1ProfCode: 'A1',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90005',
      currentCaseChapter: '05',
      hearingCode: "678",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 406,
      staff1ProfCode: 'A1',
      staff1ProfFirstName: "Donna               ",
      staff1ProfLastName: "Clayton                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90006',
      currentCaseChapter: '7A',
      hearingCode: "901",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 407,
      staff1ProfCode: 'A2',
      staff1ProfFirstName: "Brian               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B2',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '23',
      caseNumber: '90007',
      currentCaseChapter: '7B',
      hearingCode: "234",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 408,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Joe               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B1',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90008',
      currentCaseChapter: '12',
      hearingCode: "567",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 409,
      staff1ProfCode: 'A2',
      staff1ProfFirstName: "Joe               ",
      staff1ProfLastName: "Jones                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B1',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Sullivan                      ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90009',
      currentCaseChapter: '11',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 410,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90010',
      currentCaseChapter: '15',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 411,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90011',
      currentCaseChapter: '15',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 412,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90012',
      currentCaseChapter: '15',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 413,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90013',
      currentCaseChapter: '09',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 414,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90014',
      currentCaseChapter: '09',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 415,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90015',
      currentCaseChapter: '15',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 416,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90016',
      currentCaseChapter: '09',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 417,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90017',
      currentCaseChapter: '12',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 418,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90018',
      currentCaseChapter: '12',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 419,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90019',
      currentCaseChapter: '12',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 420,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90020',
      currentCaseChapter: '09',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 421,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90021',
      currentCaseChapter: '09',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
    {
      caseDiv: 422,
      staff1ProfCode: 'A3',
      staff1ProfFirstName: "Robert               ",
      staff1ProfLastName: "Stone                       ",
      staff1ProfType: "ST",
      staff1ProfTypeDescription: "STAFF MEMBER        ",
      staff2ProfCode: 'B5',
      staff2ProfFirstName: "Paul                ",
      staff2ProfLastName: "Johnson                       ",
      staff2ProfType: "ST",
      staff2ProfTypeDescription: "STAFF MEMBER        ",
      groupDesignator: 'CI',
      caseYear: '24',
      caseNumber: '90022',
      currentCaseChapter: '12',
      hearingCode: "890",
      hearingDisposition: "HD"
    },
  ]
};

export { list };
