# Frontend UI Dockerfile for E2E Testing
FROM localhost/e2e_built:latest

WORKDIR /app/user-interface

EXPOSE 3000

CMD ["sh", "-c", "node envToConfig.js && cp public/configuration.json build/configuration.json && npx vite preview --config /app/test/e2e/vite.config.e2e.mts --port 3000 --strict-port --host 0.0.0.0"]
