const list = {
  attorneyList: [
    {
      firstName: 'Susan               ',
      middleName: '',
      lastName: 'Arbeit                       ',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Mark',
      middleName: '',
      lastName: 'Bruh',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Shara',
      middleName: '',
      lastName: 'Cornell',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Brian',
      middleName: 'S',
      lastName: 'Masumoto',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Richard',
      middleName: 'C',
      lastName: 'Morrissey',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Andrea',
      middleName: 'B',
      lastName: 'Schwartz',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Paul ',
      middleName: 'K',
      lastName: 'Schwartzberg',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Shannon',
      middleName: '',
      lastName: 'Scott',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Tara',
      middleName: '',
      lastName: 'Tiantian',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Andy',
      middleName: '',
      lastName: 'Velez-Rivera',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Daniel',
      middleName: '',
      lastName: 'Rudewicz',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Annie',
      middleName: '',
      lastName: 'Wells',
      generation: '',
      office: 'Manhattan',
    },
    {
      firstName: 'Greg',
      middleName: 'M',
      lastName: 'Zipes',
      generation: '',
      office: 'Manhattan',
    },
  ],
};

export { list };
