export const OFFICES = [
  {
    divisionCode: '061',
    groupDesignator: 'AL',
    courtId: '0206',
    officeCode: '1',
    state: 'CA',
    courtName: 'Central District of California',
    courtDivisionName: 'Los Angeles',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    divisionCode: '102',
    groupDesignator: 'AL',
    courtId: '0210',
    officeCode: '2',
    state: 'TX',
    courtName: 'Northern District of Texas',
    courtDivisionName: 'Dallas',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    divisionCode: '084',
    groupDesignator: 'AL',
    courtId: '0208',
    officeCode: '4',
    state: 'FL',
    courtName: 'Southern District of Florida',
    courtDivisionName: 'Miami',
    regionId: '02',
    regionName: 'NEW YORK',
  },
  {
    divisionCode: '105',
    groupDesignator: 'AL',
    courtId: '0210',
    officeCode: '5',
    state: 'WA',
    courtName: 'Western District of Washington',
    courtDivisionName: 'Seattle',
    regionId: '02',
    regionName: 'NEW YORK',
  },
];
