name: Deploy Security Scan Storage

on:
  workflow_dispatch:

permissions: read-all

jobs:
  deploy-storage:
    name: Deploy Scan Storage
    runs-on: ubuntu-latest
    environment: security-scan
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: azure/login@f5d393ae46f8fde4be8b75f32e3fc50e654ad0ca # v3.0.1
        with:
          client-id: ${{ secrets.AZ_SECURITY_SCAN_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          environment: ${{ vars.AZURE_ENVIRONMENT }}

      - name: Deploy security scan storage account
        run: |
          az deployment group create \
            --resource-group "$RESOURCE_GROUP" \
            --template-file ops/cloud-deployment/security-scan-storage.bicep \
            --parameters storageAccountName="$STORAGE_ACCOUNT_NAME"
        env:
          RESOURCE_GROUP: ${{ secrets.AZ_SECURITY_SCAN_RG }}
          STORAGE_ACCOUNT_NAME: ${{ secrets.AZ_SECURITY_SCAN_STORAGE_NAME }}
