name: Azure Deployment - Frontend Slot Resource Creation

on:
  workflow_call:
    inputs:
      webAppName:
        required: true
        type: string
      apiFunctionName:
        required: true
        type: string
      ghaEnvironment:
        required: true
        type: string
      azResourceGrpAppEncrypted:
        required: true
        type: string
      azResourceGrpNetworkEncrypted:
        required: true
        type: string
      slotName:
        required: true
        type: string
jobs:
  deploy-frontend-slot-resources:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ghaEnvironment }}
    steps:
      - uses: actions/checkout@v3
      - uses: cloudposse/github-action-secret-outputs@main
        id: rgApp
        with:
          secret: ${{ secrets.PGP_SIGNING_PASSPHRASE }}
          op: decode
          in: ${{ inputs.azResourceGrpAppEncrypted }}
      - uses: cloudposse/github-action-secret-outputs@main
        id: rgNetwork
        with:
          secret: ${{ secrets.PGP_SIGNING_PASSPHRASE }}
          op: decode
          in: ${{ inputs.azResourceGrpNetworkEncrypted  }}
      - name: Create Webapp Slot Resource
        run: |
          webAppSubnetName="snet-${{ inputs.webAppName }}"

          echo "${{ secrets.AZURE_CREDENTIALS }}" > env.json
          AZURE_CLIENT_SECRET=$(jq -r '.clientSecret' env.json)
          AZURE_SUBSCRIPTION_ID=$(jq -r '.subscriptionId' env.json)
          AZURE_TENANT_ID=$(jq -r '.tenantId' env.json)
          AZURE_CLIENT_ID=$(jq -r '.clientId' env.json)

          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            mcr.microsoft.com/azure-cli:2.71.0 \
            bash -c '
              az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
              az account set --subscription "$AZURE_SUBSCRIPTION_ID"
              ./ops/scripts/pipeline/slots/az-slot-web-resource-deploy.sh \
                --resourceGroup ${{ steps.rgApp.outputs.out }} \
                --webappName ${{ inputs.webappName }} \
                --apiFunctionName ${{ inputs.apiFunctionName }} \
                --slotName ${{ inputs.slotName }} \
                --subscription ${{ secrets.AZURE_SUBSCRIPTION }} \
                --network-rg ${{ steps.rgNetwork.outputs.out }} \
                --vnet ${{ vars.AZ_NETWORK_VNET_NAME }} \
                --subnet $webAppSubnetName
            '
