name: TypeScript Type Check

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci --include=dev
      - name: Build Common
        run: npm run build:common
      - name: Run TypeScript Type Check
        run: npm run typecheck
