name: End-to-end Tests

on:
  workflow_call:
    inputs:
      apiFunctionName:
        required: true
        type: string
      dataflowsFunctionName:
        required: true
        type: string
      slotName:
        required: true
        type: string
      webappName:
        required: true
        type: string
      stackName:
        required: true
        type: string
      azResourceGrpAppEncrypted:
        required: true
        type: string
      ghaEnvironment:
        required: true
        type: string
      branchHashId:
        required: true
        type: string

jobs:
  playwright-e2e-test:
    environment: ${{ inputs.ghaEnvironment }}
    runs-on: ubuntu-latest
    env:
      priority: 201
    steps:
      - name: Get source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ vars.AZURE_ENVIRONMENT }}

      - uses: cloudposse/github-action-secret-outputs@67ae2f7ee1890986ba0012bacd079a5a36ecb449 # main
        id: rgApp
        with:
          secret: ${{ secrets.PGP_SIGNING_PASSPHRASE }}
          op: decode
          in: ${{ inputs.azResourceGrpAppEncrypted }}

      - name: Enable GHA runner access
        run: |
          ./ops/scripts/pipeline/dev-add-allowed-ip.sh \
          -g ${{ steps.rgApp.outputs.out }} \
          -s ${{ inputs.stackName }} \
          -p ${{ env.priority }} \
          --slot-name ${{ inputs.slotName }} \
          --is-cicd

          ./ops/scripts/pipeline/add-sql-firewall-rule.sh \
          -g ${{ secrets.AZURE_RG }} \
          --stack-name ${{ inputs.stackName }} \
          --server-name ${{ secrets.AZ_SQL_SERVER_NAME }}

          if [[ "${{ inputs.ghaEnvironment }}" == "Main-Gov" ]]; then
            ./ops/scripts/pipeline/add-cosmos-firewall-rule.sh \
            -g ${{ secrets.AZURE_RG }} \
            --account-name ${{ secrets.AZ_COSMOS_MONGO_ACCOUNT_NAME }}
          fi

      - name: Install Application Node Dependencies
        run: npm ci

      - name: Install E2E Node dependencies
        working-directory: test/e2e
        run: |
          npm ci
          npx playwright install chromium msedge

      - name: Seed e2e database
        run: |
          # Seed MongoDB
          e2eDatabaseName="${{ secrets.AZ_COSMOS_DATABASE_NAME }}-e2e"
          if [[ ${{ inputs.ghaEnvironment }} != "Main-Gov" ]]; then
            e2eDatabaseName="${e2eDatabaseName}-${{ inputs.branchHashId }}"
          fi

          export MONGO_CONNECTION_STRING="$(az cosmosdb keys list \
            -g ${{ secrets.AZURE_RG }} \
            -n ${{ secrets.AZ_COSMOS_MONGO_ACCOUNT_NAME }} \
            --type connection-strings \
            --query "connectionStrings[?description=='Primary MongoDB Connection String'].connectionString" \
            -o tsv)"
          export COSMOS_DATABASE_NAME="${e2eDatabaseName}"

          echo "Seeding E2E MongoDB..."
          (cd ./test/e2e && npm run seed)

          # Seed SQL Server
          e2eSqlDatabaseName="CAMS_E2E"
          if [[ ${{ inputs.ghaEnvironment }} != "Main-Gov" ]]; then
            e2eSqlDatabaseName="CAMS_E2E-${{ inputs.branchHashId }}"
          fi

          echo "Seeding E2E SQL Server..."
          sql_hostname_suffix=$(az cloud show --query "suffixes.sqlServerHostname" -o tsv)
          sa_user=$(az sql server show -g "${{ secrets.AZURE_RG }}" -n "${{ secrets.AZ_SQL_SERVER_NAME }}" --query administratorLogin -o tsv)
          export LOCAL_MSSQL_HOST="${{ secrets.AZ_SQL_SERVER_NAME }}${sql_hostname_suffix}"
          export LOCAL_MSSQL_USER="${sa_user}"
          export LOCAL_MSSQL_PASS="${{ secrets.MSSQL_PASS }}"
          export MSSQL_DATABASE_DXTR="${e2eSqlDatabaseName}"
          export MSSQL_ENCRYPT=true
          export MSSQL_TRUST_UNSIGNED_CERT=false
          (cd ./test/e2e && npm run seed:sql)

      - name: Run E2E Tests
        id: e2eTests
        working-directory: test/e2e
        run: |
          echo "Running Playwright Tests..."
          mkdir -p playwright/.auth
          SLOT_NAME=${{ inputs.slotName }} OKTA_USER_NAME=${{ secrets.OKTA_USER_NAME }} OKTA_PASSWORD=${{ secrets.OKTA_PASSWORD }} TARGET_HOST=https://${{ inputs.webappName }}-${{ inputs.slotName }}.azurewebsites.us CAMS_LOGIN_PROVIDER=${{ vars.CAMS_LOGIN_PROVIDER }} npx playwright test --reporter=list,html

      - name: Upload report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: always()
        with:
          name: playwright-report
          path: test/e2e/playwright-report/
          retention-days: 30

      - name: Disable GHA runner access
        if: always()
        run: |
          name="gha-${{ env.priority }}-${{ inputs.stackName }}"
          ./ops/scripts/pipeline/dev-rm-allowed-ip.sh \
          -g ${{ steps.rgApp.outputs.out }} \
          -s ${{ inputs.stackName }} \
          -r ${name:0:32} \
          --slot-name ${{ inputs.slotName }}

          ./ops/scripts/pipeline/add-sql-firewall-rule.sh \
          -g ${{ secrets.AZURE_RG }} \
          --stack-name ${{ inputs.stackName }} \
          --server-name ${{ secrets.AZ_SQL_SERVER_NAME }} \
          --delete

          if [[ "${{ inputs.ghaEnvironment }}" == "Main-Gov" ]]; then
            ./ops/scripts/pipeline/add-cosmos-firewall-rule.sh \
            -g ${{ secrets.AZURE_RG }} \
            --account-name ${{ secrets.AZ_COSMOS_MONGO_ACCOUNT_NAME }} \
            --delete
          fi
