name: End-to-end Tests

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      node-version:
        required: true
        type: string

permissions: read-all

jobs:
  playwright-accessibility-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      CI: true
    steps:
      - name: Get source code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Node dependencies
        run: |
          npm ci
          npm install serve -g

      - name: Run UI in mock mode
        run: |
          export CAMS_USE_FAKE_API=true
          export CAMS_LOGIN_PROVIDER=none
          npm run build:user-interface
          pushd ${{ inputs.path }}
          serve -s build &
          if ! timeout 120s sh -c 'until nc -z localhost 3000; do sleep 1; done'; then
              echo "Webapp check timed out"
              exit 1
          fi
          popd

      - name: Install Playwright Browsers
        working-directory: ${{ inputs.path }}
        run: npx playwright install --with-deps chromium msedge

      - name: Run Playwright a11y Tests
        id: playwrightA11yTests
        run: npm run test:a11y --workspace=user-interface

      - name: Upload report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-a11y-report
          path: ${{ inputs.path }}/playwright-report/
          retention-days: 30
