name: Smoke Test

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      hostSuffix:
        required: true
        type: string
      webappName:
        required: true
        type: string
      apiName:
        required: true
        type: string
      slotName:
        required: false
        type: string

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - name: Health check api
        run: |
          ./ops/scripts/pipeline/endpoint-test.sh \
          --apiName ${{ inputs.apiName }} \
          --webappName ${{ inputs.webappName }} \
          --hostSuffix ${{ inputs.hostSuffix }} \
          --slotName ${{ inputs.slotName }}
