name: Knip Unused Code Check

on:
  workflow_call:

jobs:
  knip:
    name: Knip
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci --include=dev
      - name: Run Knip
        run: npm run knip
