name: Static Code Analysis Scan

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  security-sca-scan:
    runs-on: ubuntu-latest
    name: Scan repository ${{ inputs.path }} lib with Veracode SCA

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Veracode SCA for ${{ inputs.path }}
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          SRCCLR_REGION: ${{ secrets.SRCCLR_REGION }}
        uses: veracode/veracode-sca@v2.1.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false
          path: ${{ inputs.path }}
