on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          short_hash="${GITHUB_SHA::7}"
          full_message=$(cat <<EOF
              ${{ inputs.message }}
              • *Branch:* ${{ github.ref_name }}
              • *Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|$short_hash>
              • *Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Workflow>
              EOF
            )
          curl -X POST -H 'Content-type: application/json' \
            --data "$(jq -n --arg text "$full_message" '{text: $text}')" \
            "$SLACK_WEBHOOK_URL"
