name: Validations

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  frontend:
    uses: ./.github/workflows/reusable-unit-test.yml
    with:
      path: user-interface
      node-version: ${{ inputs.node-version }}

  backend:
    uses: ./.github/workflows/reusable-unit-test.yml
    with:
      path: backend/functions
      node-version: ${{ inputs.node-version }}

  common:
    uses: ./.github/workflows/reusable-unit-test.yml
    with:
      path: common
      node-version: ${{ inputs.node-version }}
