name: Azure Deployment - Backend Slot Creation

on:
  workflow_call:
    inputs:
      webappName:
        required: true
        type: string
      apiFunctionName:
        required: true
        type: string
      dataflowsFunctionName:
        required: true
        type: string
      ghaEnvironment:
        required: true
        type: string
      azResourceGrpAppEncrypted:
        required: true
        type: string
      azResourceGrpNetworkEncrypted:
        required: true
        type: string
      slotName:
        required: true
        type: string
      environmentHash:
        required: true
        type: string
jobs:
  build-azure-cli-image:
    uses: ./.github/workflows/build-azure-cli-image.yml
    permissions:
      contents: read
      packages: write

  deploy-frontend-slot-resources:
    needs: build-azure-cli-image
    uses: ./.github/workflows/reusable-frontend-slot.yml
    with:
      webAppName: ${{ inputs.webappName }}
      apiFunctionName: ${{ inputs.apiFunctionName }}
      ghaEnvironment: ${{ inputs.ghaEnvironment }}
      azResourceGrpAppEncrypted: ${{ inputs.azResourceGrpAppEncrypted }}
      azResourceGrpNetworkEncrypted: ${{ inputs.azResourceGrpNetworkEncrypted }}
      slotName: ${{ inputs.slotName }}
    secrets: inherit # pragma: allowlist secret

  deploy-backend-slot-resources:
    needs: build-azure-cli-image
    uses: ./.github/workflows/reusable-backend-slot.yml
    with:
      webappName: ${{ inputs.webappName }}
      apiFunctionName: ${{ inputs.apiFunctionName }}
      dataflowsFunctionName: ${{ inputs.dataflowsFunctionName }}
      ghaEnvironment: ${{ inputs.ghaEnvironment }}
      azResourceGrpAppEncrypted: ${{ inputs.azResourceGrpAppEncrypted }}
      azResourceGrpNetworkEncrypted: ${{ inputs.azResourceGrpNetworkEncrypted }}
      slotName: ${{ inputs.slotName }}
      environmentHash: ${{ inputs.environmentHash }}
    secrets: inherit # pragma: allowlist secret
