name: Azure Deployment - Backend Slot Creation

on:
  workflow_call:
    inputs:
      webappName:
        required: true
        type: string
      apiFunctionName:
        required: true
        type: string
      dataflowsFunctionName:
        required: true
        type: string
      ghaEnvironment:
        required: true
        type: string
      azResourceGrpAppEncrypted:
        required: true
        type: string
      azResourceGrpNetworkEncrypted:
        required: true
        type: string
      slotName:
        required: true
        type: string
      environmentHash:
        required: true
        type: string
jobs:
  compute-container-image:
    runs-on: ubuntu-latest
    outputs:
      container-image: ${{ steps.set.outputs.container-image }}
    steps:
      - name: Compute lowercase container image
        id: set
        shell: bash
        run: |
          echo "container-image=ghcr.io/${GITHUB_REPOSITORY,,}/azure-cli-runner:azure-cli-2.71.0" >> "$GITHUB_OUTPUT"

  deploy-backend-slot-resources:
    needs: [compute-container-image]
    uses: ./.github/workflows/reusable-backend-slot.yml
    with:
      webappName: ${{ inputs.webappName }}
      apiFunctionName: ${{ inputs.apiFunctionName }}
      dataflowsFunctionName: ${{ inputs.dataflowsFunctionName }}
      ghaEnvironment: ${{ inputs.ghaEnvironment }}
      azResourceGrpAppEncrypted: ${{ inputs.azResourceGrpAppEncrypted }}
      azResourceGrpNetworkEncrypted: ${{ inputs.azResourceGrpNetworkEncrypted }}
      slotName: ${{ inputs.slotName }}
      environmentHash: ${{ inputs.environmentHash }}
      containerImage: ${{ needs.compute-container-image.outputs.container-image }}
    secrets: inherit # pragma: allowlist secret
