name: Test Action Linter

on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Print build info
        id: build-info
        run: |
          echo "Printing build info"
                   echo "Azure Plan Type: ${{ vars.AZ_PLAN_TYPE }}"
            echo "Environment: ${{ vars.ENVIRONMENT }}"
                echo "Target Azure Cloud: ${{ vars.AZURE_ENVIRONMENT }}"
             echo "Git SHA: ${{ github.sha }}"
          echo "Hello \
             World"
